DROP TABLE IF EXISTS modlogs

DROP TABLE IF EXISTS join_leave_logs;

DROP TABLE IF EXISTS messages;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS songs;

DROP TABLE IF EXISTS reddit_posts;

DROP TABLE IF EXISTS youtube_videos;