version = "2"

[linters]
default = "none"
enable = [
    "govet",
    "ineffassign",
    "staticcheck",
    "sloglint",
    "whitespace",
    "errname",
    "errorlint",
    "importas"
]

[formatters]
enable = ["gofmt"]
