// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_memory.sql

package db

import (
	"context"
)

const deleteAgentMemory = `-- name: DeleteAgentMemory :execrows
DELETE FROM agent_memory WHERE id = $1 AND guild_id = $2
`

type DeleteAgentMemoryParams struct {
	ID      int64 `json:"id"`
	GuildID int64 `json:"guildId"`
}

// Scoped to guild_id so the "forget" tool can only remove a row the caller's
// own guild owns, even though a memory id is otherwise a bare integer.
func (q *Queries) DeleteAgentMemory(ctx context.Context, arg DeleteAgentMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentMemory, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const evictOldAgentMemory = `-- name: EvictOldAgentMemory :exec
DELETE FROM agent_memory AS m
WHERE m.guild_id = $1 AND m.scope = $2 AND m.scope_id = $3
  AND m.id NOT IN (
      SELECT id FROM agent_memory
      WHERE guild_id = $1 AND scope = $2 AND scope_id = $3
      ORDER BY created_at DESC
      LIMIT $4
  )
`

type EvictOldAgentMemoryParams struct {
	GuildID   int64  `json:"guildId"`
	Scope     string `json:"scope"`
	ScopeID   int64  `json:"scopeId"`
	KeepCount int32  `json:"keepCount"`
}

// Runs after every insert so a single scope can never accumulate unbounded
// rows -- every kept row is folded into every future system prompt, so this
// is a cost control as much as tidiness.
func (q *Queries) EvictOldAgentMemory(ctx context.Context, arg EvictOldAgentMemoryParams) error {
	_, err := q.db.Exec(ctx, evictOldAgentMemory,
		arg.GuildID,
		arg.Scope,
		arg.ScopeID,
		arg.KeepCount,
	)
	return err
}

const getAgentMemories = `-- name: GetAgentMemories :many
SELECT id, scope, scope_id, guild_id, content, created_at FROM agent_memory
WHERE guild_id = $1 AND scope = $2 AND scope_id = $3
ORDER BY created_at DESC
LIMIT $4
`

type GetAgentMemoriesParams struct {
	GuildID int64  `json:"guildId"`
	Scope   string `json:"scope"`
	ScopeID int64  `json:"scopeId"`
	Limit   int32  `json:"limit"`
}

// Newest first, capped by the caller -- this is what gets folded into every
// system prompt, so the caller (stmpdbot/ai/memory.go) always passes a small
// limit.
func (q *Queries) GetAgentMemories(ctx context.Context, arg GetAgentMemoriesParams) ([]AgentMemory, error) {
	rows, err := q.db.Query(ctx, getAgentMemories,
		arg.GuildID,
		arg.Scope,
		arg.ScopeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMemory
	for rows.Next() {
		var i AgentMemory
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.GuildID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAgentMemory = `-- name: InsertAgentMemory :one
INSERT INTO agent_memory (scope, scope_id, guild_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, scope, scope_id, guild_id, content, created_at
`

type InsertAgentMemoryParams struct {
	Scope   string `json:"scope"`
	ScopeID int64  `json:"scopeId"`
	GuildID int64  `json:"guildId"`
	Content string `json:"content"`
}

func (q *Queries) InsertAgentMemory(ctx context.Context, arg InsertAgentMemoryParams) (AgentMemory, error) {
	row := q.db.QueryRow(ctx, insertAgentMemory,
		arg.Scope,
		arg.ScopeID,
		arg.GuildID,
		arg.Content,
	)
	var i AgentMemory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.GuildID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
