// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anniversaries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAnniversaryDay = `-- name: ClaimAnniversaryDay :execrows
INSERT INTO anniversary_posts (guild_id, local_date, song_count)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id, local_date) DO NOTHING
`

type ClaimAnniversaryDayParams struct {
	GuildID   int64       `json:"guildId"`
	LocalDate pgtype.Date `json:"localDate"`
	SongCount int32       `json:"songCount"`
}

// Claims a guild's post for one local day, atomically. Returns 1 when this caller
// won the claim and should send, 0 when the day was already taken.
//
// The insert is the claim, so two ticks racing each other -- or two bot instances --
// cannot both post. HasPostedAnniversaries above is only a cheap pre-filter to keep
// the songs query from running every five minutes until local midnight; this is what
// actually decides.
//
// Claimed before the messages go out, not after. A crash mid-send costs one day's
// post; a crash before the claim would repost the whole day on the next tick, and of
// the two, quiet is the safer failure -- the same reasoning as MarkSongAnnounced.
func (q *Queries) ClaimAnniversaryDay(ctx context.Context, arg ClaimAnniversaryDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAnniversaryDay, arg.GuildID, arg.LocalDate, arg.SongCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnniversaryGuilds = `-- name: GetAnniversaryGuilds :many
SELECT guild_id,
       anniversary_notifications_channel,
       anniversary_notifications_role,
       anniversary_hour,
       anniversary_timezone
FROM guilds
WHERE anniversary_notifications_channel IS NOT NULL
`

type GetAnniversaryGuildsRow struct {
	GuildID                         int64       `json:"guildId"`
	AnniversaryNotificationsChannel pgtype.Int8 `json:"anniversaryNotificationsChannel"`
	AnniversaryNotificationsRole    pgtype.Int8 `json:"anniversaryNotificationsRole"`
	AnniversaryHour                 int32       `json:"anniversaryHour"`
	AnniversaryTimezone             string      `json:"anniversaryTimezone"`
}

// Every guild with the feature switched on. The scheduler needs the hour and the
// timezone alongside the channel, so this cannot share the shape of the other
// Get*NotificationChannels queries, which only ever return a channel and a role.
func (q *Queries) GetAnniversaryGuilds(ctx context.Context) ([]GetAnniversaryGuildsRow, error) {
	rows, err := q.db.Query(ctx, getAnniversaryGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnniversaryGuildsRow
	for rows.Next() {
		var i GetAnniversaryGuildsRow
		if err := rows.Scan(
			&i.GuildID,
			&i.AnniversaryNotificationsChannel,
			&i.AnniversaryNotificationsRole,
			&i.AnniversaryHour,
			&i.AnniversaryTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongAnniversaries = `-- name: GetSongAnniversaries :many
SELECT songs.id, songs.name, songs.artists, songs.thumbnail_url, songs.spotify_url, songs.apple_music_url, songs.youtube_url, songs.lyrics, songs.is_unreleased, songs.beatport_id, songs.mix_name, songs.release_date, songs.release_name, songs.genre, songs.sub_genre, songs.bpm, songs.musical_key, songs.length_ms, songs.beatport_updated, songs.source, songs.first_seen_at, songs.announced_at, songs.stmpd_synced_at, songs.deezer_url, songs.tidal_url, songs.amazon_music_url, songs.youtube_music_url, songs.beatport_url, songs.beatport_release_id, songs.stmpd_slug, songs.match_key, songs.base_key, songs.parent_song_id, songs.is_instrumental, songs.is_collection, songs.beatport_slug, songs.normalized_name, songs.lrclib_id, songs.lrclib_checked_at, songs.lrclib_misses,
       (EXTRACT(YEAR FROM $1::date)
        - EXTRACT(YEAR FROM to_date(release_date, 'YYYY-MM-DD')))::int AS years_old
FROM songs
WHERE parent_song_id IS NULL
  AND NOT is_collection
  AND release_date IS NOT NULL
  AND right(release_date, 5) = ANY($2::text[])
  AND to_date(release_date, 'YYYY-MM-DD') < $1::date
ORDER BY release_date
`

type GetSongAnniversariesParams struct {
	Today     pgtype.Date `json:"today"`
	MonthDays []string    `json:"monthDays"`
}

type GetSongAnniversariesRow struct {
	Song     Song  `json:"song"`
	YearsOld int32 `json:"yearsOld"`
}

// Canonical, non-collection songs released on this month/day in an earlier year.
//
// month_day is 'MM-DD' and is matched with right(), which is what idx_songs_anniversary
// indexes -- to_date() is only stable, so it cannot carry an index. The date
// comparison is what makes "earlier year" true: without it a song released this
// morning would be announced as its own zeroth anniversary.
func (q *Queries) GetSongAnniversaries(ctx context.Context, arg GetSongAnniversariesParams) ([]GetSongAnniversariesRow, error) {
	rows, err := q.db.Query(ctx, getSongAnniversaries, arg.Today, arg.MonthDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongAnniversariesRow
	for rows.Next() {
		var i GetSongAnniversariesRow
		if err := rows.Scan(
			&i.Song.ID,
			&i.Song.Name,
			&i.Song.Artists,
			&i.Song.ThumbnailUrl,
			&i.Song.SpotifyUrl,
			&i.Song.AppleMusicUrl,
			&i.Song.YoutubeUrl,
			&i.Song.Lyrics,
			&i.Song.IsUnreleased,
			&i.Song.BeatportID,
			&i.Song.MixName,
			&i.Song.ReleaseDate,
			&i.Song.ReleaseName,
			&i.Song.Genre,
			&i.Song.SubGenre,
			&i.Song.Bpm,
			&i.Song.MusicalKey,
			&i.Song.LengthMs,
			&i.Song.BeatportUpdated,
			&i.Song.Source,
			&i.Song.FirstSeenAt,
			&i.Song.AnnouncedAt,
			&i.Song.StmpdSyncedAt,
			&i.Song.DeezerUrl,
			&i.Song.TidalUrl,
			&i.Song.AmazonMusicUrl,
			&i.Song.YoutubeMusicUrl,
			&i.Song.BeatportUrl,
			&i.Song.BeatportReleaseID,
			&i.Song.StmpdSlug,
			&i.Song.MatchKey,
			&i.Song.BaseKey,
			&i.Song.ParentSongID,
			&i.Song.IsInstrumental,
			&i.Song.IsCollection,
			&i.Song.BeatportSlug,
			&i.Song.NormalizedName,
			&i.Song.LrclibID,
			&i.Song.LrclibCheckedAt,
			&i.Song.LrclibMisses,
			&i.YearsOld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPostedAnniversaries = `-- name: HasPostedAnniversaries :one
SELECT EXISTS (
    SELECT 1 FROM anniversary_posts WHERE guild_id = $1 AND local_date = $2
)
`

type HasPostedAnniversariesParams struct {
	GuildID   int64       `json:"guildId"`
	LocalDate pgtype.Date `json:"localDate"`
}

func (q *Queries) HasPostedAnniversaries(ctx context.Context, arg HasPostedAnniversariesParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostedAnniversaries, arg.GuildID, arg.LocalDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setAnniversaryChannel = `-- name: SetAnniversaryChannel :exec
UPDATE guilds SET anniversary_notifications_channel = $2 WHERE guild_id = $1
`

type SetAnniversaryChannelParams struct {
	GuildID                         int64       `json:"guildId"`
	AnniversaryNotificationsChannel pgtype.Int8 `json:"anniversaryNotificationsChannel"`
}

func (q *Queries) SetAnniversaryChannel(ctx context.Context, arg SetAnniversaryChannelParams) error {
	_, err := q.db.Exec(ctx, setAnniversaryChannel, arg.GuildID, arg.AnniversaryNotificationsChannel)
	return err
}

const setAnniversaryRole = `-- name: SetAnniversaryRole :exec
UPDATE guilds SET anniversary_notifications_role = $2 WHERE guild_id = $1
`

type SetAnniversaryRoleParams struct {
	GuildID                      int64       `json:"guildId"`
	AnniversaryNotificationsRole pgtype.Int8 `json:"anniversaryNotificationsRole"`
}

func (q *Queries) SetAnniversaryRole(ctx context.Context, arg SetAnniversaryRoleParams) error {
	_, err := q.db.Exec(ctx, setAnniversaryRole, arg.GuildID, arg.AnniversaryNotificationsRole)
	return err
}

const setAnniversarySchedule = `-- name: SetAnniversarySchedule :exec
UPDATE guilds SET anniversary_hour = $2, anniversary_timezone = $3 WHERE guild_id = $1
`

type SetAnniversaryScheduleParams struct {
	GuildID             int64  `json:"guildId"`
	AnniversaryHour     int32  `json:"anniversaryHour"`
	AnniversaryTimezone string `json:"anniversaryTimezone"`
}

func (q *Queries) SetAnniversarySchedule(ctx context.Context, arg SetAnniversaryScheduleParams) error {
	_, err := q.db.Exec(ctx, setAnniversarySchedule, arg.GuildID, arg.AnniversaryHour, arg.AnniversaryTimezone)
	return err
}
