// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package db

import (
	"context"
)

const clearAnnouncementFailures = `-- name: ClearAnnouncementFailures :exec
UPDATE song_announcements SET failed_at = NULL
WHERE channel_id = $1 AND failed_at IS NOT NULL
`

// Called after a successful post to a channel: whatever the permission problem was,
// it is over, so the parked messages in that channel become editable again.
func (q *Queries) ClearAnnouncementFailures(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, clearAnnouncementFailures, channelID)
	return err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM song_announcements WHERE guild_id = $1 AND message_id = $2
`

type DeleteAnnouncementParams struct {
	GuildID   int64 `json:"guildId"`
	MessageID int64 `json:"messageId"`
}

// The message or its channel is gone. There is nothing left to correct, and keeping
// the row would retry forever.
func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, arg.GuildID, arg.MessageID)
	return err
}

const getAnnouncementsToRefresh = `-- name: GetAnnouncementsToRefresh :many
SELECT a.song_id, a.guild_id, a.channel_id, a.message_id, a.buttons_key, a.edit_count,
       s.id, s.name, s.artists, s.thumbnail_url, s.spotify_url, s.apple_music_url, s.youtube_url, s.lyrics, s.is_unreleased, s.beatport_id, s.mix_name, s.release_date, s.release_name, s.genre, s.sub_genre, s.bpm, s.musical_key, s.length_ms, s.beatport_updated, s.source, s.first_seen_at, s.announced_at, s.stmpd_synced_at, s.deezer_url, s.tidal_url, s.amazon_music_url, s.youtube_music_url, s.beatport_url, s.beatport_release_id, s.stmpd_slug, s.match_key, s.base_key, s.parent_song_id, s.is_instrumental, s.is_collection, s.beatport_slug, s.normalized_name, s.lrclib_id, s.lrclib_checked_at, s.lrclib_misses
FROM song_announcements a
JOIN songs s ON s.id = a.song_id
WHERE a.failed_at IS NULL
  AND a.edit_count < 5
  AND a.posted_at > NOW() - INTERVAL '60 days'
  AND (a.edited_at IS NULL OR a.edited_at < NOW() - INTERVAL '1 hour')
ORDER BY a.posted_at DESC
LIMIT $1
`

type GetAnnouncementsToRefreshRow struct {
	SongID     int64  `json:"songId"`
	GuildID    int64  `json:"guildId"`
	ChannelID  int64  `json:"channelId"`
	MessageID  int64  `json:"messageId"`
	ButtonsKey string `json:"buttonsKey"`
	EditCount  int16  `json:"editCount"`
	Song       Song   `json:"song"`
}

// Recent announcements whose buttons may have moved on.
//
// Four bounds, each doing a different job. failed_at parks a message the bot cannot
// currently edit. edit_count stops correcting a message that has been corrected five
// times, which means something upstream is flapping rather than settling. edited_at
// caps any one message at one edit an hour. posted_at is what keeps the candidate set
// from growing by every song the bot ever announces: a release's links stop arriving
// within weeks.
//
// The buttons themselves are compared in Go, not here -- the fingerprint is a hash of
// what utils.GetSongButtons would render, and SQL cannot compute it.
func (q *Queries) GetAnnouncementsToRefresh(ctx context.Context, lim int32) ([]GetAnnouncementsToRefreshRow, error) {
	rows, err := q.db.Query(ctx, getAnnouncementsToRefresh, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnnouncementsToRefreshRow
	for rows.Next() {
		var i GetAnnouncementsToRefreshRow
		if err := rows.Scan(
			&i.SongID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.ButtonsKey,
			&i.EditCount,
			&i.Song.ID,
			&i.Song.Name,
			&i.Song.Artists,
			&i.Song.ThumbnailUrl,
			&i.Song.SpotifyUrl,
			&i.Song.AppleMusicUrl,
			&i.Song.YoutubeUrl,
			&i.Song.Lyrics,
			&i.Song.IsUnreleased,
			&i.Song.BeatportID,
			&i.Song.MixName,
			&i.Song.ReleaseDate,
			&i.Song.ReleaseName,
			&i.Song.Genre,
			&i.Song.SubGenre,
			&i.Song.Bpm,
			&i.Song.MusicalKey,
			&i.Song.LengthMs,
			&i.Song.BeatportUpdated,
			&i.Song.Source,
			&i.Song.FirstSeenAt,
			&i.Song.AnnouncedAt,
			&i.Song.StmpdSyncedAt,
			&i.Song.DeezerUrl,
			&i.Song.TidalUrl,
			&i.Song.AmazonMusicUrl,
			&i.Song.YoutubeMusicUrl,
			&i.Song.BeatportUrl,
			&i.Song.BeatportReleaseID,
			&i.Song.StmpdSlug,
			&i.Song.MatchKey,
			&i.Song.BaseKey,
			&i.Song.ParentSongID,
			&i.Song.IsInstrumental,
			&i.Song.IsCollection,
			&i.Song.BeatportSlug,
			&i.Song.NormalizedName,
			&i.Song.LrclibID,
			&i.Song.LrclibCheckedAt,
			&i.Song.LrclibMisses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSongAnnouncement = `-- name: InsertSongAnnouncement :exec
INSERT INTO song_announcements (song_id, guild_id, channel_id, message_id, buttons_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (guild_id, message_id) DO NOTHING
`

type InsertSongAnnouncementParams struct {
	SongID     int64  `json:"songId"`
	GuildID    int64  `json:"guildId"`
	ChannelID  int64  `json:"channelId"`
	MessageID  int64  `json:"messageId"`
	ButtonsKey string `json:"buttonsKey"`
}

// ON CONFLICT DO NOTHING because the send path is best-effort bookkeeping: a message
// id we already hold is not a problem worth failing an announcement over.
func (q *Queries) InsertSongAnnouncement(ctx context.Context, arg InsertSongAnnouncementParams) error {
	_, err := q.db.Exec(ctx, insertSongAnnouncement,
		arg.SongID,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.ButtonsKey,
	)
	return err
}

const markAnnouncementEdited = `-- name: MarkAnnouncementEdited :exec
UPDATE song_announcements
SET buttons_key = $1, edited_at = NOW(), edit_count = edit_count + 1
WHERE guild_id = $2 AND message_id = $3
`

type MarkAnnouncementEditedParams struct {
	ButtonsKey string `json:"buttonsKey"`
	GuildID    int64  `json:"guildId"`
	MessageID  int64  `json:"messageId"`
}

// Writes the new fingerprint, so the same change can never be detected twice.
func (q *Queries) MarkAnnouncementEdited(ctx context.Context, arg MarkAnnouncementEditedParams) error {
	_, err := q.db.Exec(ctx, markAnnouncementEdited, arg.ButtonsKey, arg.GuildID, arg.MessageID)
	return err
}

const markAnnouncementFailed = `-- name: MarkAnnouncementFailed :exec
UPDATE song_announcements SET failed_at = NOW()
WHERE guild_id = $1 AND message_id = $2
`

type MarkAnnouncementFailedParams struct {
	GuildID   int64 `json:"guildId"`
	MessageID int64 `json:"messageId"`
}

// Discord refused the edit for a reason that may resolve itself -- usually the bot
// losing access to the channel. Parked, not deleted: permissions come back, and this
// row is the only record of where the message is.
func (q *Queries) MarkAnnouncementFailed(ctx context.Context, arg MarkAnnouncementFailedParams) error {
	_, err := q.db.Exec(ctx, markAnnouncementFailed, arg.GuildID, arg.MessageID)
	return err
}
