// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backgrounds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGuildBackground = `-- name: AddGuildBackground :exec
INSERT INTO guild_backgrounds (guild_id, background_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGuildBackgroundParams struct {
	GuildID      int64 `json:"guildId"`
	BackgroundID int64 `json:"backgroundId"`
}

func (q *Queries) AddGuildBackground(ctx context.Context, arg AddGuildBackgroundParams) error {
	_, err := q.db.Exec(ctx, addGuildBackground, arg.GuildID, arg.BackgroundID)
	return err
}

const clearGuildBackgrounds = `-- name: ClearGuildBackgrounds :exec
DELETE FROM guild_backgrounds WHERE guild_id = $1
`

func (q *Queries) ClearGuildBackgrounds(ctx context.Context, guildID int64) error {
	_, err := q.db.Exec(ctx, clearGuildBackgrounds, guildID)
	return err
}

const createBackground = `-- name: CreateBackground :one
INSERT INTO backgrounds (filename, uploaded_by)
VALUES ($1, $2)
ON CONFLICT (filename) DO UPDATE SET filename = EXCLUDED.filename
RETURNING id, filename, uploaded_by, created_at
`

type CreateBackgroundParams struct {
	Filename   string      `json:"filename"`
	UploadedBy pgtype.Int8 `json:"uploadedBy"`
}

// The ON CONFLICT arm is a no-op update rather than DO NOTHING so RETURNING
// always yields a row -- this doubles as the idempotent "ensure the built-in
// backgrounds are seeded" call made on every bot startup.
func (q *Queries) CreateBackground(ctx context.Context, arg CreateBackgroundParams) (Background, error) {
	row := q.db.QueryRow(ctx, createBackground, arg.Filename, arg.UploadedBy)
	var i Background
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGuildBackgroundSettings = `-- name: GetGuildBackgroundSettings :one
SELECT background_mode, background_cycle_background_id
FROM guilds
WHERE guild_id = $1
`

type GetGuildBackgroundSettingsRow struct {
	BackgroundMode              string      `json:"backgroundMode"`
	BackgroundCycleBackgroundID pgtype.Int8 `json:"backgroundCycleBackgroundId"`
}

func (q *Queries) GetGuildBackgroundSettings(ctx context.Context, guildID int64) (GetGuildBackgroundSettingsRow, error) {
	row := q.db.QueryRow(ctx, getGuildBackgroundSettings, guildID)
	var i GetGuildBackgroundSettingsRow
	err := row.Scan(&i.BackgroundMode, &i.BackgroundCycleBackgroundID)
	return i, err
}

const listBackgrounds = `-- name: ListBackgrounds :many
SELECT id, filename, uploaded_by, created_at FROM backgrounds ORDER BY id
`

func (q *Queries) ListBackgrounds(ctx context.Context) ([]Background, error) {
	rows, err := q.db.Query(ctx, listBackgrounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Background
	for rows.Next() {
		var i Background
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildBackgrounds = `-- name: ListGuildBackgrounds :many
SELECT b.id, b.filename, b.uploaded_by, b.created_at FROM backgrounds b
JOIN guild_backgrounds gb ON gb.background_id = b.id
WHERE gb.guild_id = $1
ORDER BY b.id
`

func (q *Queries) ListGuildBackgrounds(ctx context.Context, guildID int64) ([]Background, error) {
	rows, err := q.db.Query(ctx, listGuildBackgrounds, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Background
	for rows.Next() {
		var i Background
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGuildBackgroundCyclePosition = `-- name: SetGuildBackgroundCyclePosition :exec
UPDATE guilds SET background_cycle_background_id = $2 WHERE guild_id = $1
`

type SetGuildBackgroundCyclePositionParams struct {
	GuildID                     int64       `json:"guildId"`
	BackgroundCycleBackgroundID pgtype.Int8 `json:"backgroundCycleBackgroundId"`
}

func (q *Queries) SetGuildBackgroundCyclePosition(ctx context.Context, arg SetGuildBackgroundCyclePositionParams) error {
	_, err := q.db.Exec(ctx, setGuildBackgroundCyclePosition, arg.GuildID, arg.BackgroundCycleBackgroundID)
	return err
}

const setGuildBackgroundMode = `-- name: SetGuildBackgroundMode :exec
UPDATE guilds SET background_mode = $2 WHERE guild_id = $1
`

type SetGuildBackgroundModeParams struct {
	GuildID        int64  `json:"guildId"`
	BackgroundMode string `json:"backgroundMode"`
}

func (q *Queries) SetGuildBackgroundMode(ctx context.Context, arg SetGuildBackgroundModeParams) error {
	_, err := q.db.Exec(ctx, setGuildBackgroundMode, arg.GuildID, arg.BackgroundMode)
	return err
}
