// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configuration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds(guild_id)
VALUES ($1)
ON CONFLICT (guild_id) DO NOTHING
RETURNING guild_id, modlogs_channel, leave_join_logs_channel, youtube_notifications_channel, youtube_notifications_role, reddit_notifications_channel, reddit_notifications_role, stmpd_notifications_channel, stmpd_notifications_role, welcomes_channel, delete_logs_channel, edit_logs_channel, bot_channel, radio_voice_channel, news_role, xp_multiplier, tour_notifications_channel, tour_notifications_role, moderator_role
`

func (q *Queries) CreateGuild(ctx context.Context, guildID int64) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild, guildID)
	var i Guild
	err := row.Scan(
		&i.GuildID,
		&i.ModlogsChannel,
		&i.LeaveJoinLogsChannel,
		&i.YoutubeNotificationsChannel,
		&i.YoutubeNotificationsRole,
		&i.RedditNotificationsChannel,
		&i.RedditNotificationsRole,
		&i.StmpdNotificationsChannel,
		&i.StmpdNotificationsRole,
		&i.WelcomesChannel,
		&i.DeleteLogsChannel,
		&i.EditLogsChannel,
		&i.BotChannel,
		&i.RadioVoiceChannel,
		&i.NewsRole,
		&i.XpMultiplier,
		&i.TourNotificationsChannel,
		&i.TourNotificationsRole,
		&i.ModeratorRole,
	)
	return i, err
}

const getGuild = `-- name: GetGuild :one
SELECT guild_id, modlogs_channel, leave_join_logs_channel, youtube_notifications_channel, youtube_notifications_role, reddit_notifications_channel, reddit_notifications_role, stmpd_notifications_channel, stmpd_notifications_role, welcomes_channel, delete_logs_channel, edit_logs_channel, bot_channel, radio_voice_channel, news_role, xp_multiplier, tour_notifications_channel, tour_notifications_role, moderator_role FROM guilds WHERE guild_id = $1
`

func (q *Queries) GetGuild(ctx context.Context, guildID int64) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, guildID)
	var i Guild
	err := row.Scan(
		&i.GuildID,
		&i.ModlogsChannel,
		&i.LeaveJoinLogsChannel,
		&i.YoutubeNotificationsChannel,
		&i.YoutubeNotificationsRole,
		&i.RedditNotificationsChannel,
		&i.RedditNotificationsRole,
		&i.StmpdNotificationsChannel,
		&i.StmpdNotificationsRole,
		&i.WelcomesChannel,
		&i.DeleteLogsChannel,
		&i.EditLogsChannel,
		&i.BotChannel,
		&i.RadioVoiceChannel,
		&i.NewsRole,
		&i.XpMultiplier,
		&i.TourNotificationsChannel,
		&i.TourNotificationsRole,
		&i.ModeratorRole,
	)
	return i, err
}

const getRadioVoiceChannels = `-- name: GetRadioVoiceChannels :many
SELECT guild_id, radio_voice_channel
FROM guilds
WHERE radio_voice_channel IS NOT NULL
`

type GetRadioVoiceChannelsRow struct {
	GuildID           int64       `json:"guildId"`
	RadioVoiceChannel pgtype.Int8 `json:"radioVoiceChannel"`
}

func (q *Queries) GetRadioVoiceChannels(ctx context.Context) ([]GetRadioVoiceChannelsRow, error) {
	rows, err := q.db.Query(ctx, getRadioVoiceChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRadioVoiceChannelsRow
	for rows.Next() {
		var i GetRadioVoiceChannelsRow
		if err := rows.Scan(&i.GuildID, &i.RadioVoiceChannel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedditNotificationChannels = `-- name: GetRedditNotificationChannels :many
SELECT reddit_notifications_channel, reddit_notifications_role 
FROM guilds
WHERE reddit_notifications_channel IS NOT NULL
`

type GetRedditNotificationChannelsRow struct {
	RedditNotificationsChannel pgtype.Int8 `json:"redditNotificationsChannel"`
	RedditNotificationsRole    pgtype.Int8 `json:"redditNotificationsRole"`
}

func (q *Queries) GetRedditNotificationChannels(ctx context.Context) ([]GetRedditNotificationChannelsRow, error) {
	rows, err := q.db.Query(ctx, getRedditNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRedditNotificationChannelsRow
	for rows.Next() {
		var i GetRedditNotificationChannelsRow
		if err := rows.Scan(&i.RedditNotificationsChannel, &i.RedditNotificationsRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSTMPDNofiticationChannels = `-- name: GetSTMPDNofiticationChannels :many
SELECT stmpd_notifications_channel, stmpd_notifications_role
FROM guilds
WHERE stmpd_notifications_channel IS NOT NULL
`

type GetSTMPDNofiticationChannelsRow struct {
	StmpdNotificationsChannel pgtype.Int8 `json:"stmpdNotificationsChannel"`
	StmpdNotificationsRole    pgtype.Int8 `json:"stmpdNotificationsRole"`
}

func (q *Queries) GetSTMPDNofiticationChannels(ctx context.Context) ([]GetSTMPDNofiticationChannelsRow, error) {
	rows, err := q.db.Query(ctx, getSTMPDNofiticationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSTMPDNofiticationChannelsRow
	for rows.Next() {
		var i GetSTMPDNofiticationChannelsRow
		if err := rows.Scan(&i.StmpdNotificationsChannel, &i.StmpdNotificationsRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYoutubeNotifactionChannels = `-- name: GetYoutubeNotifactionChannels :many
SELECT youtube_notifications_channel, youtube_notifications_role 
FROM guilds
WHERE youtube_notifications_channel IS NOT NULL
`

type GetYoutubeNotifactionChannelsRow struct {
	YoutubeNotificationsChannel pgtype.Int8 `json:"youtubeNotificationsChannel"`
	YoutubeNotificationsRole    pgtype.Int8 `json:"youtubeNotificationsRole"`
}

func (q *Queries) GetYoutubeNotifactionChannels(ctx context.Context) ([]GetYoutubeNotifactionChannelsRow, error) {
	rows, err := q.db.Query(ctx, getYoutubeNotifactionChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetYoutubeNotifactionChannelsRow
	for rows.Next() {
		var i GetYoutubeNotifactionChannelsRow
		if err := rows.Scan(&i.YoutubeNotificationsChannel, &i.YoutubeNotificationsRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setModeratorRole = `-- name: SetModeratorRole :exec
UPDATE guilds
SET moderator_role = $2
WHERE guild_id = $1
`

type SetModeratorRoleParams struct {
	GuildID       int64       `json:"guildId"`
	ModeratorRole pgtype.Int8 `json:"moderatorRole"`
}

func (q *Queries) SetModeratorRole(ctx context.Context, arg SetModeratorRoleParams) error {
	_, err := q.db.Exec(ctx, setModeratorRole, arg.GuildID, arg.ModeratorRole)
	return err
}
