// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashActivePunishments = `-- name: DashActivePunishments :many
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active, audit_log_id FROM modlogs
WHERE guild_id = $1
  AND active = true
  AND expires_at IS NOT NULL
  AND expires_at > (now() AT TIME ZONE 'UTC')
ORDER BY expires_at ASC, id
LIMIT $2
`

type DashActivePunishmentsParams struct {
	GuildID int64 `json:"guildId"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) DashActivePunishments(ctx context.Context, arg DashActivePunishmentsParams) ([]Modlog, error) {
	rows, err := q.db.Query(ctx, dashActivePunishments, arg.GuildID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modlog
	for rows.Next() {
		var i Modlog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModeratorID,
			&i.LogType,
			&i.Reason,
			&i.Time,
			&i.GuildID,
			&i.ExpiresAt,
			&i.Active,
			&i.AuditLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashActivityHeatmap = `-- name: DashActivityHeatmap :many
SELECT
    EXTRACT(DOW  FROM ("timestamp" AT TIME ZONE 'UTC') AT TIME ZONE $2::text)::int AS dow,
    EXTRACT(HOUR FROM ("timestamp" AT TIME ZONE 'UTC') AT TIME ZONE $2::text)::int AS hour,
    COUNT(*)::bigint AS messages
FROM messages
WHERE guild_id = $1
  AND "timestamp" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
GROUP BY 1, 2
ORDER BY 1, 2
`

type DashActivityHeatmapParams struct {
	GuildID    int64  `json:"guildId"`
	Tz         string `json:"tz"`
	WindowDays int32  `json:"windowDays"`
}

type DashActivityHeatmapRow struct {
	Dow      int32 `json:"dow"`
	Hour     int32 `json:"hour"`
	Messages int64 `json:"messages"`
}

// Hour-of-day x day-of-week, rendered as a CSS grid rather than a chart
// library. dow is 0=Sunday, matching Postgres' EXTRACT(DOW).
func (q *Queries) DashActivityHeatmap(ctx context.Context, arg DashActivityHeatmapParams) ([]DashActivityHeatmapRow, error) {
	rows, err := q.db.Query(ctx, dashActivityHeatmap, arg.GuildID, arg.Tz, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashActivityHeatmapRow
	for rows.Next() {
		var i DashActivityHeatmapRow
		if err := rows.Scan(&i.Dow, &i.Hour, &i.Messages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashGuildOverview = `-- name: DashGuildOverview :one

SELECT
    (SELECT COUNT(*) FROM users u WHERE u.guild_id = $1)::bigint AS tracked_users,
    (SELECT COALESCE(SUM(u.messages_sent), 0) FROM users u WHERE u.guild_id = $1)::bigint AS messages_counted,
    (SELECT COALESCE(SUM(u.total_xp), 0) FROM users u WHERE u.guild_id = $1)::bigint AS total_xp,
    (SELECT COALESCE(SUM(COALESCE(u.stmpd_coins, 0) + COALESCE(u.in_hand, 0)), 0)
       FROM users u WHERE u.guild_id = $1)::bigint AS coins_in_circulation,
    (SELECT COUNT(*) FROM messages m
       WHERE m.guild_id = $1
         AND m."timestamp" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $2::int)
    )::bigint AS messages_window,
    (SELECT COUNT(*) FROM modlogs ml
       WHERE ml.guild_id = $1
         AND ml."time" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $2::int)
    )::bigint AS modlogs_window,
    (SELECT COUNT(*) FROM modlogs ml
       WHERE ml.guild_id = $1 AND ml.active = true
         AND ml.expires_at IS NOT NULL
         AND ml.expires_at > (now() AT TIME ZONE 'UTC')
    )::bigint AS active_punishments
`

type DashGuildOverviewParams struct {
	GuildID    int64 `json:"guildId"`
	WindowDays int32 `json:"windowDays"`
}

type DashGuildOverviewRow struct {
	TrackedUsers       int64 `json:"trackedUsers"`
	MessagesCounted    int64 `json:"messagesCounted"`
	TotalXp            int64 `json:"totalXp"`
	CoinsInCirculation int64 `json:"coinsInCirculation"`
	MessagesWindow     int64 `json:"messagesWindow"`
	ModlogsWindow      int64 `json:"modlogsWindow"`
	ActivePunishments  int64 `json:"activePunishments"`
}

// Overview -----------------------------------------------------------------
func (q *Queries) DashGuildOverview(ctx context.Context, arg DashGuildOverviewParams) (DashGuildOverviewRow, error) {
	row := q.db.QueryRow(ctx, dashGuildOverview, arg.GuildID, arg.WindowDays)
	var i DashGuildOverviewRow
	err := row.Scan(
		&i.TrackedUsers,
		&i.MessagesCounted,
		&i.TotalXp,
		&i.CoinsInCirculation,
		&i.MessagesWindow,
		&i.ModlogsWindow,
		&i.ActivePunishments,
	)
	return i, err
}

const dashJoinLeaveDaily = `-- name: DashJoinLeaveDaily :many

WITH days AS (
    SELECT generate_series(
        date_trunc('day', ((now() AT TIME ZONE 'UTC') AT TIME ZONE $2::text)
            - make_interval(days => $3::int - 1)),
        date_trunc('day', ((now() AT TIME ZONE 'UTC') AT TIME ZONE $2::text)),
        INTERVAL '1 day'
    ) AS day
),
events AS (
    SELECT
        date_trunc('day', ("time" AT TIME ZONE 'UTC') AT TIME ZONE $2::text) AS day,
        COUNT(*) FILTER (WHERE action = 'join')  AS joins,
        COUNT(*) FILTER (WHERE action = 'leave') AS leaves
    FROM join_leave_logs
    WHERE guild_id = $1
      AND "time" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
    GROUP BY 1
)
SELECT
    d.day::timestamp AS day,
    COALESCE(e.joins, 0)::bigint  AS joins,
    COALESCE(e.leaves, 0)::bigint AS leaves,
    (COALESCE(e.joins, 0) - COALESCE(e.leaves, 0))::bigint AS net
FROM days d
LEFT JOIN events e ON e.day = d.day
ORDER BY d.day
`

type DashJoinLeaveDailyParams struct {
	GuildID    int64  `json:"guildId"`
	Tz         string `json:"tz"`
	WindowDays int32  `json:"windowDays"`
}

type DashJoinLeaveDailyRow struct {
	Day    pgtype.Timestamp `json:"day"`
	Joins  int64            `json:"joins"`
	Leaves int64            `json:"leaves"`
	Net    int64            `json:"net"`
}

// Member growth ------------------------------------------------------------
// The generate_series join is the point of this query: without it a day with no
// joins and no leaves is a MISSING ROW, and a line chart happily draws a
// straight line across the gap -- turning "nothing happened" into what looks
// like real interpolated data.
func (q *Queries) DashJoinLeaveDaily(ctx context.Context, arg DashJoinLeaveDailyParams) ([]DashJoinLeaveDailyRow, error) {
	rows, err := q.db.Query(ctx, dashJoinLeaveDaily, arg.GuildID, arg.Tz, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashJoinLeaveDailyRow
	for rows.Next() {
		var i DashJoinLeaveDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Joins,
			&i.Leaves,
			&i.Net,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashJoinLeaveTotals = `-- name: DashJoinLeaveTotals :one
SELECT
    COUNT(*) FILTER (WHERE action = 'join')::bigint  AS joins,
    COUNT(*) FILTER (WHERE action = 'leave')::bigint AS leaves
FROM join_leave_logs
WHERE guild_id = $1
  AND "time" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $2::int)
`

type DashJoinLeaveTotalsParams struct {
	GuildID    int64 `json:"guildId"`
	WindowDays int32 `json:"windowDays"`
}

type DashJoinLeaveTotalsRow struct {
	Joins  int64 `json:"joins"`
	Leaves int64 `json:"leaves"`
}

func (q *Queries) DashJoinLeaveTotals(ctx context.Context, arg DashJoinLeaveTotalsParams) (DashJoinLeaveTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashJoinLeaveTotals, arg.GuildID, arg.WindowDays)
	var i DashJoinLeaveTotalsRow
	err := row.Scan(&i.Joins, &i.Leaves)
	return i, err
}

const dashMemberLogs = `-- name: DashMemberLogs :many
SELECT member_id, action, time, id, guild_id FROM join_leave_logs
WHERE guild_id = $1
  AND ($4::varchar IS NULL OR action = $4)
  AND ($5::bigint IS NULL OR member_id = $5)
  AND ($6::timestamp IS NULL OR "time" >= $6)
  AND ($7::timestamp IS NULL OR "time" < $7)
ORDER BY "time" DESC, id DESC
LIMIT $2 OFFSET $3
`

type DashMemberLogsParams struct {
	GuildID  int64            `json:"guildId"`
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
	Action   pgtype.Text      `json:"action"`
	MemberID pgtype.Int8      `json:"memberId"`
	After    pgtype.Timestamp `json:"after"`
	Before   pgtype.Timestamp `json:"before"`
}

func (q *Queries) DashMemberLogs(ctx context.Context, arg DashMemberLogsParams) ([]JoinLeaveLog, error) {
	rows, err := q.db.Query(ctx, dashMemberLogs,
		arg.GuildID,
		arg.Limit,
		arg.Offset,
		arg.Action,
		arg.MemberID,
		arg.After,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JoinLeaveLog
	for rows.Next() {
		var i JoinLeaveLog
		if err := rows.Scan(
			&i.MemberID,
			&i.Action,
			&i.Time,
			&i.ID,
			&i.GuildID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashMemberLogsCount = `-- name: DashMemberLogsCount :one
SELECT COUNT(*) FROM join_leave_logs
WHERE guild_id = $1
  AND ($2::varchar IS NULL OR action = $2)
  AND ($3::bigint IS NULL OR member_id = $3)
  AND ($4::timestamp IS NULL OR "time" >= $4)
  AND ($5::timestamp IS NULL OR "time" < $5)
`

type DashMemberLogsCountParams struct {
	GuildID  int64            `json:"guildId"`
	Action   pgtype.Text      `json:"action"`
	MemberID pgtype.Int8      `json:"memberId"`
	After    pgtype.Timestamp `json:"after"`
	Before   pgtype.Timestamp `json:"before"`
}

func (q *Queries) DashMemberLogsCount(ctx context.Context, arg DashMemberLogsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashMemberLogsCount,
		arg.GuildID,
		arg.Action,
		arg.MemberID,
		arg.After,
		arg.Before,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashMessagesDaily = `-- name: DashMessagesDaily :many

WITH days AS (
    SELECT generate_series(
        date_trunc('day', ((now() AT TIME ZONE 'UTC') AT TIME ZONE $2::text)
            - make_interval(days => $3::int - 1)),
        date_trunc('day', ((now() AT TIME ZONE 'UTC') AT TIME ZONE $2::text)),
        INTERVAL '1 day'
    ) AS day
),
counts AS (
    SELECT
        date_trunc('day', ("timestamp" AT TIME ZONE 'UTC') AT TIME ZONE $2::text) AS day,
        COUNT(*) AS messages,
        COUNT(DISTINCT author_id) AS active_authors
    FROM messages
    WHERE guild_id = $1
      AND "timestamp" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
    GROUP BY 1
)
SELECT
    d.day::timestamp AS day,
    COALESCE(c.messages, 0)::bigint       AS messages,
    COALESCE(c.active_authors, 0)::bigint AS active_authors
FROM days d
LEFT JOIN counts c ON c.day = d.day
ORDER BY d.day
`

type DashMessagesDailyParams struct {
	GuildID    int64  `json:"guildId"`
	Tz         string `json:"tz"`
	WindowDays int32  `json:"windowDays"`
}

type DashMessagesDailyRow struct {
	Day           pgtype.Timestamp `json:"day"`
	Messages      int64            `json:"messages"`
	ActiveAuthors int64            `json:"activeAuthors"`
}

// Message activity ---------------------------------------------------------
func (q *Queries) DashMessagesDaily(ctx context.Context, arg DashMessagesDailyParams) ([]DashMessagesDailyRow, error) {
	rows, err := q.db.Query(ctx, dashMessagesDaily, arg.GuildID, arg.Tz, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashMessagesDailyRow
	for rows.Next() {
		var i DashMessagesDailyRow
		if err := rows.Scan(&i.Day, &i.Messages, &i.ActiveAuthors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashModlogTypes = `-- name: DashModlogTypes :many
SELECT log_type, COUNT(*)::bigint AS count
FROM modlogs
WHERE guild_id = $1
GROUP BY log_type
ORDER BY count DESC
`

type DashModlogTypesRow struct {
	LogType string `json:"logType"`
	Count   int64  `json:"count"`
}

// Populates the filter dropdown from what this guild has actually recorded, so
// a log_type added in the bot needs no dashboard change to become filterable.
func (q *Queries) DashModlogTypes(ctx context.Context, guildID int64) ([]DashModlogTypesRow, error) {
	rows, err := q.db.Query(ctx, dashModlogTypes, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashModlogTypesRow
	for rows.Next() {
		var i DashModlogTypesRow
		if err := rows.Scan(&i.LogType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashModlogs = `-- name: DashModlogs :many

SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active, audit_log_id FROM modlogs
WHERE guild_id = $1
  AND ($4::varchar IS NULL OR log_type = $4)
  AND ($5::bigint IS NULL OR user_id = $5)
  AND ($6::bigint IS NULL OR moderator_id = $6)
  AND ($7::boolean IS NULL OR active = $7)
  AND ($8::timestamp IS NULL OR "time" >= $8)
  AND ($9::timestamp IS NULL OR "time" < $9)
ORDER BY "time" DESC, id DESC
LIMIT $2 OFFSET $3
`

type DashModlogsParams struct {
	GuildID     int64            `json:"guildId"`
	Limit       int32            `json:"limit"`
	Offset      int32            `json:"offset"`
	LogType     pgtype.Text      `json:"logType"`
	UserID      pgtype.Int8      `json:"userId"`
	ModeratorID pgtype.Int8      `json:"moderatorId"`
	Active      pgtype.Bool      `json:"active"`
	After       pgtype.Timestamp `json:"after"`
	Before      pgtype.Timestamp `json:"before"`
}

// Queries backing the web dashboard. They are kept in their own file because
// none of the existing ones fit: the leaderboards in users.sql hardcode
// LIMIT 10, and GetModlogsByGuild takes no filters.
//
// Two conventions here that every query in this file follows, both forced by
// the fact that modlogs.time, join_leave_logs.time and messages.timestamp are
// `timestamp without time zone` columns holding UTC instants:
//
//  1. Day and hour buckets are computed as
//     ("time" AT TIME ZONE 'UTC') AT TIME ZONE sqlc.arg('tz')
//     The first conversion reinterprets the naive value as the UTC instant it
//     actually is; the second renders it as wall-clock in the viewer's zone.
//     A plain date_trunc('day', "time") cuts days at UTC midnight, which for
//     the bot's own Asia/Kolkata is 05:30 -- so "yesterday" on the chart would
//     not be yesterday.
//
//  2. Comparisons against the current time are written
//     (now() AT TIME ZONE 'UTC')
//     rather than bare now(). now() is timestamptz, and comparing it to a naive
//     column makes Postgres convert using the session TimeZone GUC, so the
//     result would silently depend on the database container's timezone.
//
// id DESC is not decoration: bulk moderation lands many rows on the same
// timestamp, and without a deterministic tiebreak those rows shuffle between
// pages, so paging forwards shows some of them twice and skips others.
func (q *Queries) DashModlogs(ctx context.Context, arg DashModlogsParams) ([]Modlog, error) {
	rows, err := q.db.Query(ctx, dashModlogs,
		arg.GuildID,
		arg.Limit,
		arg.Offset,
		arg.LogType,
		arg.UserID,
		arg.ModeratorID,
		arg.Active,
		arg.After,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modlog
	for rows.Next() {
		var i Modlog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModeratorID,
			&i.LogType,
			&i.Reason,
			&i.Time,
			&i.GuildID,
			&i.ExpiresAt,
			&i.Active,
			&i.AuditLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashModlogsByType = `-- name: DashModlogsByType :many

SELECT log_type, COUNT(*)::bigint AS count
FROM modlogs
WHERE guild_id = $1
  AND "time" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $2::int)
GROUP BY log_type
ORDER BY count DESC
`

type DashModlogsByTypeParams struct {
	GuildID    int64 `json:"guildId"`
	WindowDays int32 `json:"windowDays"`
}

type DashModlogsByTypeRow struct {
	LogType string `json:"logType"`
	Count   int64  `json:"count"`
}

// Moderation ---------------------------------------------------------------
func (q *Queries) DashModlogsByType(ctx context.Context, arg DashModlogsByTypeParams) ([]DashModlogsByTypeRow, error) {
	rows, err := q.db.Query(ctx, dashModlogsByType, arg.GuildID, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashModlogsByTypeRow
	for rows.Next() {
		var i DashModlogsByTypeRow
		if err := rows.Scan(&i.LogType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashModlogsCount = `-- name: DashModlogsCount :one
SELECT COUNT(*) FROM modlogs
WHERE guild_id = $1
  AND ($2::varchar IS NULL OR log_type = $2)
  AND ($3::bigint IS NULL OR user_id = $3)
  AND ($4::bigint IS NULL OR moderator_id = $4)
  AND ($5::boolean IS NULL OR active = $5)
  AND ($6::timestamp IS NULL OR "time" >= $6)
  AND ($7::timestamp IS NULL OR "time" < $7)
`

type DashModlogsCountParams struct {
	GuildID     int64            `json:"guildId"`
	LogType     pgtype.Text      `json:"logType"`
	UserID      pgtype.Int8      `json:"userId"`
	ModeratorID pgtype.Int8      `json:"moderatorId"`
	Active      pgtype.Bool      `json:"active"`
	After       pgtype.Timestamp `json:"after"`
	Before      pgtype.Timestamp `json:"before"`
}

func (q *Queries) DashModlogsCount(ctx context.Context, arg DashModlogsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashModlogsCount,
		arg.GuildID,
		arg.LogType,
		arg.UserID,
		arg.ModeratorID,
		arg.Active,
		arg.After,
		arg.Before,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashModlogsDaily = `-- name: DashModlogsDaily :many
SELECT
    date_trunc('day', ("time" AT TIME ZONE 'UTC') AT TIME ZONE $2::text)::timestamp AS day,
    log_type,
    COUNT(*)::bigint AS count
FROM modlogs
WHERE guild_id = $1
  AND "time" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
GROUP BY 1, 2
ORDER BY 1, 2
`

type DashModlogsDailyParams struct {
	GuildID    int64  `json:"guildId"`
	Tz         string `json:"tz"`
	WindowDays int32  `json:"windowDays"`
}

type DashModlogsDailyRow struct {
	Day     pgtype.Timestamp `json:"day"`
	LogType string           `json:"logType"`
	Count   int64            `json:"count"`
}

func (q *Queries) DashModlogsDaily(ctx context.Context, arg DashModlogsDailyParams) ([]DashModlogsDailyRow, error) {
	rows, err := q.db.Query(ctx, dashModlogsDaily, arg.GuildID, arg.Tz, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashModlogsDailyRow
	for rows.Next() {
		var i DashModlogsDailyRow
		if err := rows.Scan(&i.Day, &i.LogType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashTopChannels = `-- name: DashTopChannels :many
SELECT channel_id, COUNT(*)::bigint AS messages
FROM messages
WHERE guild_id = $1
  AND "timestamp" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
GROUP BY channel_id
ORDER BY messages DESC, channel_id
LIMIT $2
`

type DashTopChannelsParams struct {
	GuildID    int64 `json:"guildId"`
	Limit      int32 `json:"limit"`
	WindowDays int32 `json:"windowDays"`
}

type DashTopChannelsRow struct {
	ChannelID int64 `json:"channelId"`
	Messages  int64 `json:"messages"`
}

func (q *Queries) DashTopChannels(ctx context.Context, arg DashTopChannelsParams) ([]DashTopChannelsRow, error) {
	rows, err := q.db.Query(ctx, dashTopChannels, arg.GuildID, arg.Limit, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashTopChannelsRow
	for rows.Next() {
		var i DashTopChannelsRow
		if err := rows.Scan(&i.ChannelID, &i.Messages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashTopMembers = `-- name: DashTopMembers :many

SELECT
    id,
    messages_sent,
    total_xp,
    stmpd_coins,
    in_hand,
    (COALESCE(stmpd_coins, 0) + COALESCE(in_hand, 0))::bigint AS net_worth
FROM users
WHERE guild_id = $1
ORDER BY
    CASE WHEN $3::text = 'messages' THEN messages_sent END DESC NULLS LAST,
    CASE WHEN $3::text = 'xp'       THEN total_xp      END DESC NULLS LAST,
    CASE WHEN $3::text = 'coins'
         THEN COALESCE(stmpd_coins, 0) + COALESCE(in_hand, 0)       END DESC NULLS LAST,
    id
LIMIT $2
`

type DashTopMembersParams struct {
	GuildID int64  `json:"guildId"`
	Limit   int32  `json:"limit"`
	Sort    string `json:"sort"`
}

type DashTopMembersRow struct {
	ID           int64       `json:"id"`
	MessagesSent pgtype.Int4 `json:"messagesSent"`
	TotalXp      pgtype.Int4 `json:"totalXp"`
	StmpdCoins   pgtype.Int8 `json:"stmpdCoins"`
	InHand       pgtype.Int8 `json:"inHand"`
	NetWorth     int64       `json:"netWorth"`
}

// Economy and levels -------------------------------------------------------
// One query, three orderings. The existing leaderboards in users.sql back live
// slash commands and hardcode LIMIT 10, so they are left alone.
// The trailing `id` is a deterministic tiebreak; without it members tied on 0
// shuffle position between renders.
func (q *Queries) DashTopMembers(ctx context.Context, arg DashTopMembersParams) ([]DashTopMembersRow, error) {
	rows, err := q.db.Query(ctx, dashTopMembers, arg.GuildID, arg.Limit, arg.Sort)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashTopMembersRow
	for rows.Next() {
		var i DashTopMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.MessagesSent,
			&i.TotalXp,
			&i.StmpdCoins,
			&i.InHand,
			&i.NetWorth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashTopModerators = `-- name: DashTopModerators :many
SELECT
    moderator_id,
    COUNT(*)::bigint AS actions,
    COUNT(*) FILTER (WHERE log_type IN ('ban', 'tempban', 'softban'))::bigint AS bans,
    COUNT(*) FILTER (WHERE log_type IN ('mute', 'tempmute'))::bigint          AS mutes,
    COUNT(*) FILTER (WHERE log_type = 'kick')::bigint                         AS kicks,
    MAX("time")::timestamp AS last_action
FROM modlogs
WHERE guild_id = $1
  AND "time" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
GROUP BY moderator_id
ORDER BY actions DESC, moderator_id
LIMIT $2
`

type DashTopModeratorsParams struct {
	GuildID    int64 `json:"guildId"`
	Limit      int32 `json:"limit"`
	WindowDays int32 `json:"windowDays"`
}

type DashTopModeratorsRow struct {
	ModeratorID int64            `json:"moderatorId"`
	Actions     int64            `json:"actions"`
	Bans        int64            `json:"bans"`
	Mutes       int64            `json:"mutes"`
	Kicks       int64            `json:"kicks"`
	LastAction  pgtype.Timestamp `json:"lastAction"`
}

func (q *Queries) DashTopModerators(ctx context.Context, arg DashTopModeratorsParams) ([]DashTopModeratorsRow, error) {
	rows, err := q.db.Query(ctx, dashTopModerators, arg.GuildID, arg.Limit, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashTopModeratorsRow
	for rows.Next() {
		var i DashTopModeratorsRow
		if err := rows.Scan(
			&i.ModeratorID,
			&i.Actions,
			&i.Bans,
			&i.Mutes,
			&i.Kicks,
			&i.LastAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashTopPosters = `-- name: DashTopPosters :many
SELECT author_id, COUNT(*)::bigint AS messages
FROM messages
WHERE guild_id = $1
  AND "timestamp" >= (now() AT TIME ZONE 'UTC') - make_interval(days => $3::int)
  AND author_id IS NOT NULL
GROUP BY author_id
ORDER BY messages DESC, author_id
LIMIT $2
`

type DashTopPostersParams struct {
	GuildID    int64 `json:"guildId"`
	Limit      int32 `json:"limit"`
	WindowDays int32 `json:"windowDays"`
}

type DashTopPostersRow struct {
	AuthorID pgtype.Int8 `json:"authorId"`
	Messages int64       `json:"messages"`
}

func (q *Queries) DashTopPosters(ctx context.Context, arg DashTopPostersParams) ([]DashTopPostersRow, error) {
	rows, err := q.db.Query(ctx, dashTopPosters, arg.GuildID, arg.Limit, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashTopPostersRow
	for rows.Next() {
		var i DashTopPostersRow
		if err := rows.Scan(&i.AuthorID, &i.Messages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashXPDistribution = `-- name: DashXPDistribution :many
SELECT
    width_bucket(
        u.total_xp, 0,
        GREATEST((SELECT MAX(mx.total_xp) FROM users mx WHERE mx.guild_id = $1), 1),
        20
    ) AS bucket,
    MIN(u.total_xp)::int AS min_xp,
    MAX(u.total_xp)::int AS max_xp,
    COUNT(*)::bigint     AS members
FROM users u
WHERE u.guild_id = $1 AND u.total_xp > 0
GROUP BY bucket
ORDER BY bucket
`

type DashXPDistributionRow struct {
	Bucket  int32 `json:"bucket"`
	MinXp   int32 `json:"minXp"`
	MaxXp   int32 `json:"maxXp"`
	Members int64 `json:"members"`
}

func (q *Queries) DashXPDistribution(ctx context.Context, guildID int64) ([]DashXPDistributionRow, error) {
	rows, err := q.db.Query(ctx, dashXPDistribution, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashXPDistributionRow
	for rows.Next() {
		var i DashXPDistributionRow
		if err := rows.Scan(
			&i.Bucket,
			&i.MinXp,
			&i.MaxXp,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
