// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: join_leave_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeaveJoinLogsChannel = `-- name: GetLeaveJoinLogsChannel :one
SELECT leave_join_logs_channel
FROM guilds
WHERE guild_id = $1
`

func (q *Queries) GetLeaveJoinLogsChannel(ctx context.Context, guildID int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getLeaveJoinLogsChannel, guildID)
	var leave_join_logs_channel pgtype.Int8
	err := row.Scan(&leave_join_logs_channel)
	return leave_join_logs_channel, err
}

const logMemberJoin = `-- name: LogMemberJoin :exec
INSERT INTO join_leave_logs (member_id, action, time)
VALUES ($1, 'join', $2)
`

type LogMemberJoinParams struct {
	MemberID int64            `json:"memberId"`
	Time     pgtype.Timestamp `json:"time"`
}

func (q *Queries) LogMemberJoin(ctx context.Context, arg LogMemberJoinParams) error {
	_, err := q.db.Exec(ctx, logMemberJoin, arg.MemberID, arg.Time)
	return err
}

const logMemberLeave = `-- name: LogMemberLeave :exec
INSERT INTO join_leave_logs (member_id, action, time)
VALUES ($1, 'leave', $2)
`

type LogMemberLeaveParams struct {
	MemberID int64            `json:"memberId"`
	Time     pgtype.Timestamp `json:"time"`
}

func (q *Queries) LogMemberLeave(ctx context.Context, arg LogMemberLeaveParams) error {
	_, err := q.db.Exec(ctx, logMemberLeave, arg.MemberID, arg.Time)
	return err
}
