// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeleteLogsChannel = `-- name: GetDeleteLogsChannel :one
SELECT delete_logs_channel
FROM guilds
WHERE guild_id = $1
`

func (q *Queries) GetDeleteLogsChannel(ctx context.Context, guildID int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getDeleteLogsChannel, guildID)
	var delete_logs_channel pgtype.Int8
	err := row.Scan(&delete_logs_channel)
	return delete_logs_channel, err
}

const getEditLogsChannel = `-- name: GetEditLogsChannel :one
SELECT edit_logs_channel
FROM guilds
WHERE guild_id = $1
`

func (q *Queries) GetEditLogsChannel(ctx context.Context, guildID int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getEditLogsChannel, guildID)
	var edit_logs_channel pgtype.Int8
	err := row.Scan(&edit_logs_channel)
	return edit_logs_channel, err
}
