// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JoinLeaveLog struct {
	MemberID int64            `json:"memberId"`
	Action   string           `json:"action"`
	Time     pgtype.Timestamp `json:"time"`
}

type Message struct {
	MessageID int64            `json:"messageId"`
	ChannelID int64            `json:"channelId"`
	AuthorID  int64            `json:"authorId"`
	Content   string           `json:"content"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}

type Modlog struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"userId"`
	ModeratorID int64            `json:"moderatorId"`
	LogType     string           `json:"logType"`
	Reason      pgtype.Text      `json:"reason"`
	Time        pgtype.Timestamp `json:"time"`
}

type RedditPost struct {
	PostID string `json:"postId"`
}

type Song struct {
	Alias        pgtype.Text `json:"alias"`
	Name         string      `json:"name"`
	Lyrics       pgtype.Text `json:"lyrics"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
}

type Tag struct {
	CreatorID int64            `json:"creatorId"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Uses      pgtype.Int4      `json:"uses"`
	Name      string           `json:"name"`
}

type User struct {
	ID           int64            `json:"id"`
	MessagesSent pgtype.Int4      `json:"messagesSent"`
	TotalXp      pgtype.Int4      `json:"totalXp"`
	LastXpAdded  pgtype.Timestamp `json:"lastXpAdded"`
	GarrixCoins  pgtype.Int8      `json:"garrixCoins"`
	InHand       pgtype.Int8      `json:"inHand"`
}

type YoutubeVideo struct {
	VideoID string `json:"videoId"`
}
