// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modlogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModlog = `-- name: CreateModlog :one
INSERT INTO modlogs (
    user_id,
    moderator_id,
    guild_id,
    log_type,
    reason,
    expires_at,
    active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active
`

type CreateModlogParams struct {
	UserID      int64            `json:"userId"`
	ModeratorID int64            `json:"moderatorId"`
	GuildID     int64            `json:"guildId"`
	LogType     string           `json:"logType"`
	Reason      pgtype.Text      `json:"reason"`
	ExpiresAt   pgtype.Timestamp `json:"expiresAt"`
	Active      pgtype.Bool      `json:"active"`
}

func (q *Queries) CreateModlog(ctx context.Context, arg CreateModlogParams) (Modlog, error) {
	row := q.db.QueryRow(ctx, createModlog,
		arg.UserID,
		arg.ModeratorID,
		arg.GuildID,
		arg.LogType,
		arg.Reason,
		arg.ExpiresAt,
		arg.Active,
	)
	var i Modlog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModeratorID,
		&i.LogType,
		&i.Reason,
		&i.Time,
		&i.GuildID,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const deactivateModlog = `-- name: DeactivateModlog :exec
UPDATE modlogs
SET active = false
WHERE id = $1
`

func (q *Queries) DeactivateModlog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateModlog, id)
	return err
}

const getActiveTempBanForUser = `-- name: GetActiveTempBanForUser :one
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE user_id = $1 
  AND guild_id = $2 
  AND log_type = 'tempban' 
  AND active = true 
  AND expires_at > NOW()
LIMIT 1
`

type GetActiveTempBanForUserParams struct {
	UserID  int64 `json:"userId"`
	GuildID int64 `json:"guildId"`
}

func (q *Queries) GetActiveTempBanForUser(ctx context.Context, arg GetActiveTempBanForUserParams) (Modlog, error) {
	row := q.db.QueryRow(ctx, getActiveTempBanForUser, arg.UserID, arg.GuildID)
	var i Modlog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModeratorID,
		&i.LogType,
		&i.Reason,
		&i.Time,
		&i.GuildID,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const getActiveTempMuteForUser = `-- name: GetActiveTempMuteForUser :one
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE user_id = $1 
  AND guild_id = $2 
  AND log_type = 'tempmute' 
  AND active = true 
  AND expires_at > NOW()
LIMIT 1
`

type GetActiveTempMuteForUserParams struct {
	UserID  int64 `json:"userId"`
	GuildID int64 `json:"guildId"`
}

func (q *Queries) GetActiveTempMuteForUser(ctx context.Context, arg GetActiveTempMuteForUserParams) (Modlog, error) {
	row := q.db.QueryRow(ctx, getActiveTempMuteForUser, arg.UserID, arg.GuildID)
	var i Modlog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModeratorID,
		&i.LogType,
		&i.Reason,
		&i.Time,
		&i.GuildID,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const getActiveTemporaryActions = `-- name: GetActiveTemporaryActions :many
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE guild_id = $1 
  AND active = true 
  AND expires_at IS NOT NULL 
  AND expires_at > NOW()
ORDER BY expires_at ASC
`

func (q *Queries) GetActiveTemporaryActions(ctx context.Context, guildID int64) ([]Modlog, error) {
	rows, err := q.db.Query(ctx, getActiveTemporaryActions, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modlog
	for rows.Next() {
		var i Modlog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModeratorID,
			&i.LogType,
			&i.Reason,
			&i.Time,
			&i.GuildID,
			&i.ExpiresAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredTemporaryActions = `-- name: GetExpiredTemporaryActions :many
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE guild_id = $1 
  AND active = true 
  AND expires_at IS NOT NULL 
  AND expires_at <= NOW()
`

func (q *Queries) GetExpiredTemporaryActions(ctx context.Context, guildID int64) ([]Modlog, error) {
	rows, err := q.db.Query(ctx, getExpiredTemporaryActions, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modlog
	for rows.Next() {
		var i Modlog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModeratorID,
			&i.LogType,
			&i.Reason,
			&i.Time,
			&i.GuildID,
			&i.ExpiresAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModlogByID = `-- name: GetModlogByID :one
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE id = $1
`

func (q *Queries) GetModlogByID(ctx context.Context, id int64) (Modlog, error) {
	row := q.db.QueryRow(ctx, getModlogByID, id)
	var i Modlog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModeratorID,
		&i.LogType,
		&i.Reason,
		&i.Time,
		&i.GuildID,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const getModlogsByGuild = `-- name: GetModlogsByGuild :many
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE guild_id = $1
ORDER BY time DESC
LIMIT $2 OFFSET $3
`

type GetModlogsByGuildParams struct {
	GuildID int64 `json:"guildId"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetModlogsByGuild(ctx context.Context, arg GetModlogsByGuildParams) ([]Modlog, error) {
	rows, err := q.db.Query(ctx, getModlogsByGuild, arg.GuildID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modlog
	for rows.Next() {
		var i Modlog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModeratorID,
			&i.LogType,
			&i.Reason,
			&i.Time,
			&i.GuildID,
			&i.ExpiresAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModlogsByUser = `-- name: GetModlogsByUser :many
SELECT id, user_id, moderator_id, log_type, reason, time, guild_id, expires_at, active FROM modlogs
WHERE user_id = $1 AND guild_id = $2
ORDER BY time DESC
LIMIT $3 OFFSET $4
`

type GetModlogsByUserParams struct {
	UserID  int64 `json:"userId"`
	GuildID int64 `json:"guildId"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetModlogsByUser(ctx context.Context, arg GetModlogsByUserParams) ([]Modlog, error) {
	rows, err := q.db.Query(ctx, getModlogsByUser,
		arg.UserID,
		arg.GuildID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modlog
	for rows.Next() {
		var i Modlog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModeratorID,
			&i.LogType,
			&i.Reason,
			&i.Time,
			&i.GuildID,
			&i.ExpiresAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModlogsByUserCount = `-- name: GetModlogsByUserCount :one
SELECT COUNT(*) FROM modlogs
WHERE user_id = $1 AND guild_id = $2
`

type GetModlogsByUserCountParams struct {
	UserID  int64 `json:"userId"`
	GuildID int64 `json:"guildId"`
}

func (q *Queries) GetModlogsByUserCount(ctx context.Context, arg GetModlogsByUserCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getModlogsByUserCount, arg.UserID, arg.GuildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
