// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notificications.sql

package db

import (
	"context"
)

const insertRedditPost = `-- name: InsertRedditPost :exec
INSERT INTO reddit_posts(post_id) VALUES ($1)
`

func (q *Queries) InsertRedditPost(ctx context.Context, postID string) error {
	_, err := q.db.Exec(ctx, insertRedditPost, postID)
	return err
}

const insertYoutubeVideo = `-- name: InsertYoutubeVideo :exec
INSERT INTO youtube_videos(video_id) VALUES  ($1)
`

func (q *Queries) InsertYoutubeVideo(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, insertYoutubeVideo, videoID)
	return err
}
