// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs_dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashRepointAnnouncements = `-- name: DashRepointAnnouncements :execrows
UPDATE song_announcements SET song_id = $1
WHERE song_id = $2
`

type DashRepointAnnouncementsParams struct {
	NewSong int64 `json:"newSong"`
	OldSong int64 `json:"oldSong"`
}

// Moves a song's posted announcements onto the row that survives a merge.
//
// Without this the merge loses them: song_announcements.song_id is ON DELETE CASCADE,
// so deleting the merged-away row deletes its announcement history with it, and the
// refresh loop then has no record that those messages exist.
func (q *Queries) DashRepointAnnouncements(ctx context.Context, arg DashRepointAnnouncementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, dashRepointAnnouncements, arg.NewSong, arg.OldSong)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dashRepointChildren = `-- name: DashRepointChildren :execrows
UPDATE songs SET parent_song_id = $1
WHERE parent_song_id = $2 AND id <> $1
`

type DashRepointChildrenParams struct {
	NewParent pgtype.Int8 `json:"newParent"`
	OldParent pgtype.Int8 `json:"oldParent"`
}

// Moves every rendition of one song onto another. Used when promoting a rendition to be
// the canonical row: its siblings have to follow it, or they are left pointing at a row
// that is now a child and the tree is two levels deep.
func (q *Queries) DashRepointChildren(ctx context.Context, arg DashRepointChildrenParams) (int64, error) {
	result, err := q.db.Exec(ctx, dashRepointChildren, arg.NewParent, arg.OldParent)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dashSetSongParent = `-- name: DashSetSongParent :one
UPDATE songs
SET parent_song_id = $1::bigint,
    -- ARRAY[...] rather than a bare string: ` + "`" + `text[] || 'parent_song_id'` + "`" + ` makes
    -- Postgres read the literal as an array literal and fail with 22P02, since an
    -- unadorned word is not a valid array literal.
    locked_fields = CASE WHEN 'parent_song_id' = ANY(locked_fields) THEN locked_fields
                         ELSE locked_fields || ARRAY['parent_song_id'::text] END
WHERE id = $2
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text
`

type DashSetSongParentParams struct {
	ParentSongID pgtype.Int8 `json:"parentSongId"`
	ID           int64       `json:"id"`
}

// Re-parenting from the dashboard, which unlike the automated writer is never refused
// by a lock: a person moving a row is the authority the lock protects. Locking the
// column is what stops the next link-remix-parents run from moving it back.
func (q *Queries) DashSetSongParent(ctx context.Context, arg DashSetSongParentParams) (Song, error) {
	row := q.db.QueryRow(ctx, dashSetSongParent, arg.ParentSongID, arg.ID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const dashSongAnnouncements = `-- name: DashSongAnnouncements :many
SELECT guild_id, channel_id, message_id, buttons_key, posted_at, edited_at,
       edit_count, failed_at
FROM song_announcements
WHERE song_id = $1
ORDER BY posted_at DESC
`

type DashSongAnnouncementsRow struct {
	GuildID    int64              `json:"guildId"`
	ChannelID  int64              `json:"channelId"`
	MessageID  int64              `json:"messageId"`
	ButtonsKey string             `json:"buttonsKey"`
	PostedAt   pgtype.Timestamptz `json:"postedAt"`
	EditedAt   pgtype.Timestamptz `json:"editedAt"`
	EditCount  int16              `json:"editCount"`
	FailedAt   pgtype.Timestamptz `json:"failedAt"`
}

// Where a song has been posted, for the song page. idx_song_announcements_song covers
// this; there was no per-song listing before because the bot only ever reads
// announcements by age, to decide what to refresh.
func (q *Queries) DashSongAnnouncements(ctx context.Context, songID int64) ([]DashSongAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, dashSongAnnouncements, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashSongAnnouncementsRow
	for rows.Next() {
		var i DashSongAnnouncementsRow
		if err := rows.Scan(
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.ButtonsKey,
			&i.PostedAt,
			&i.EditedAt,
			&i.EditCount,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashSongCandidates = `-- name: DashSongCandidates :many
SELECT id, name, artists, mix_name, release_date, source, parent_song_id, is_collection,
       thumbnail_url
FROM songs
WHERE id <> $1
  AND COALESCE(search_text, LOWER(artists || ' ' || name || ' ' || COALESCE(mix_name, '')))
        LIKE ALL ($2::text[])
ORDER BY (parent_song_id IS NULL) DESC, release_date DESC NULLS LAST, id
LIMIT 25
`

type DashSongCandidatesParams struct {
	ExcludeID int64    `json:"excludeId"`
	Terms     []string `json:"terms"`
}

type DashSongCandidatesRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	MixName      pgtype.Text `json:"mixName"`
	ReleaseDate  pgtype.Text `json:"releaseDate"`
	Source       string      `json:"source"`
	ParentSongID pgtype.Int8 `json:"parentSongId"`
	IsCollection bool        `json:"isCollection"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
}

// Rows a given song could be filed under or merged with: same folded terms, never
// itself. Deliberately not restricted to canonical rows -- promoting a rendition is a
// thing the page has to allow, and the handler enforces the tree's shape.
func (q *Queries) DashSongCandidates(ctx context.Context, arg DashSongCandidatesParams) ([]DashSongCandidatesRow, error) {
	rows, err := q.db.Query(ctx, dashSongCandidates, arg.ExcludeID, arg.Terms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashSongCandidatesRow
	for rows.Next() {
		var i DashSongCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.Source,
			&i.ParentSongID,
			&i.IsCollection,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashSongs = `-- name: DashSongs :many

SELECT s.id, s.name, s.artists, s.mix_name, s.release_date, s.release_name, s.source,
       s.thumbnail_url, s.parent_song_id, s.is_collection, s.is_unreleased,
       s.is_instrumental, s.locked_fields, s.beatport_id, s.stmpd_slug,
       (s.lyrics IS NOT NULL)::boolean AS has_lyrics,
       (s.spotify_url IS NOT NULL OR s.youtube_url IS NOT NULL
        OR s.apple_music_url IS NOT NULL OR s.beatport_url IS NOT NULL
        OR s.deezer_url IS NOT NULL OR s.tidal_url IS NOT NULL
        OR s.amazon_music_url IS NOT NULL OR s.youtube_music_url IS NOT NULL)::boolean AS has_links,
       (SELECT count(*) FROM songs c WHERE c.parent_song_id = s.id)::bigint AS rendition_count
FROM songs s
WHERE COALESCE(s.search_text,
               LOWER(s.artists || ' ' || s.name || ' ' || COALESCE(s.mix_name, '')))
        LIKE ALL ($1::text[])
  AND ($2::varchar IS NULL OR s.source = $2)
  AND ($3::boolean IS NULL OR s.is_collection = $3)
  AND ($4::boolean IS NULL
       OR (s.parent_song_id IS NULL) = $4)
  AND ($5::boolean IS NULL
       OR (s.lyrics IS NOT NULL) = $5)
  AND ($6::boolean IS NULL
       OR (s.thumbnail_url IS NOT NULL) = $6)
  AND ($7::boolean IS NULL
       OR (s.spotify_url IS NOT NULL OR s.youtube_url IS NOT NULL
           OR s.apple_music_url IS NOT NULL OR s.beatport_url IS NOT NULL
           OR s.deezer_url IS NOT NULL OR s.tidal_url IS NOT NULL
           OR s.amazon_music_url IS NOT NULL OR s.youtube_music_url IS NOT NULL)
          = $7)
  -- The problem filter passes the ids the audit flagged. Keeping it as a plain id set
  -- means every invariant is filterable without a query per check, and the filters
  -- above still compose with it.
  AND ($8::bigint[] IS NULL OR s.id = ANY($8::bigint[]))
ORDER BY s.release_date DESC NULLS LAST, s.id DESC
LIMIT $10 OFFSET $9
`

type DashSongsParams struct {
	Terms        []string    `json:"terms"`
	Source       pgtype.Text `json:"source"`
	IsCollection pgtype.Bool `json:"isCollection"`
	IsCanonical  pgtype.Bool `json:"isCanonical"`
	HasLyrics    pgtype.Bool `json:"hasLyrics"`
	HasArtwork   pgtype.Bool `json:"hasArtwork"`
	HasLinks     pgtype.Bool `json:"hasLinks"`
	Ids          []int64     `json:"ids"`
	Off          int32       `json:"off"`
	Lim          int32       `json:"lim"`
}

type DashSongsRow struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Artists        string      `json:"artists"`
	MixName        pgtype.Text `json:"mixName"`
	ReleaseDate    pgtype.Text `json:"releaseDate"`
	ReleaseName    pgtype.Text `json:"releaseName"`
	Source         string      `json:"source"`
	ThumbnailUrl   pgtype.Text `json:"thumbnailUrl"`
	ParentSongID   pgtype.Int8 `json:"parentSongId"`
	IsCollection   bool        `json:"isCollection"`
	IsUnreleased   bool        `json:"isUnreleased"`
	IsInstrumental bool        `json:"isInstrumental"`
	LockedFields   []string    `json:"lockedFields"`
	BeatportID     pgtype.Int4 `json:"beatportId"`
	StmpdSlug      pgtype.Text `json:"stmpdSlug"`
	HasLyrics      bool        `json:"hasLyrics"`
	HasLinks       bool        `json:"hasLinks"`
	RenditionCount int64       `json:"renditionCount"`
}

// Queries backing the dashboard's catalogue pages.
//
// They are separate from songs.sql because none of the bot's song queries fit: those
// exist to serve one song to one Discord user, so they filter renditions and
// collections out of sight and cap at twenty rows. The dashboard's job is the opposite
// -- show the table as it actually is, including the rows the bot deliberately hides,
// because a row nobody can see is a row nobody can fix.
//
// Search matches per term against the folded haystack rather than as one contiguous
// LIKE; see the note on GetSongsLike in songs.sql. COALESCE onto an unfolded expression
// keeps a row inserted before the next rekey-songs findable.
// id is the tiebreak for the same reason DashModlogs orders by id DESC: a whole release
// shares one date, so without it those rows shuffle between pages and paging forwards
// shows some twice while skipping others.
func (q *Queries) DashSongs(ctx context.Context, arg DashSongsParams) ([]DashSongsRow, error) {
	rows, err := q.db.Query(ctx, dashSongs,
		arg.Terms,
		arg.Source,
		arg.IsCollection,
		arg.IsCanonical,
		arg.HasLyrics,
		arg.HasArtwork,
		arg.HasLinks,
		arg.Ids,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashSongsRow
	for rows.Next() {
		var i DashSongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.ReleaseName,
			&i.Source,
			&i.ThumbnailUrl,
			&i.ParentSongID,
			&i.IsCollection,
			&i.IsUnreleased,
			&i.IsInstrumental,
			&i.LockedFields,
			&i.BeatportID,
			&i.StmpdSlug,
			&i.HasLyrics,
			&i.HasLinks,
			&i.RenditionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashSongsCount = `-- name: DashSongsCount :one
SELECT COUNT(*) FROM songs s
WHERE COALESCE(s.search_text,
               LOWER(s.artists || ' ' || s.name || ' ' || COALESCE(s.mix_name, '')))
        LIKE ALL ($1::text[])
  AND ($2::varchar IS NULL OR s.source = $2)
  AND ($3::boolean IS NULL OR s.is_collection = $3)
  AND ($4::boolean IS NULL
       OR (s.parent_song_id IS NULL) = $4)
  AND ($5::boolean IS NULL
       OR (s.lyrics IS NOT NULL) = $5)
  AND ($6::boolean IS NULL
       OR (s.thumbnail_url IS NOT NULL) = $6)
  AND ($7::boolean IS NULL
       OR (s.spotify_url IS NOT NULL OR s.youtube_url IS NOT NULL
           OR s.apple_music_url IS NOT NULL OR s.beatport_url IS NOT NULL
           OR s.deezer_url IS NOT NULL OR s.tidal_url IS NOT NULL
           OR s.amazon_music_url IS NOT NULL OR s.youtube_music_url IS NOT NULL)
          = $7)
  AND ($8::bigint[] IS NULL OR s.id = ANY($8::bigint[]))
`

type DashSongsCountParams struct {
	Terms        []string    `json:"terms"`
	Source       pgtype.Text `json:"source"`
	IsCollection pgtype.Bool `json:"isCollection"`
	IsCanonical  pgtype.Bool `json:"isCanonical"`
	HasLyrics    pgtype.Bool `json:"hasLyrics"`
	HasArtwork   pgtype.Bool `json:"hasArtwork"`
	HasLinks     pgtype.Bool `json:"hasLinks"`
	Ids          []int64     `json:"ids"`
}

func (q *Queries) DashSongsCount(ctx context.Context, arg DashSongsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashSongsCount,
		arg.Terms,
		arg.Source,
		arg.IsCollection,
		arg.IsCanonical,
		arg.HasLyrics,
		arg.HasArtwork,
		arg.HasLinks,
		arg.Ids,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashUnlockSongField = `-- name: DashUnlockSongField :one
UPDATE songs SET locked_fields = array_remove(locked_fields, $1::text)
WHERE id = $2
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text
`

type DashUnlockSongFieldParams struct {
	Field string `json:"field"`
	ID    int64  `json:"id"`
}

// Hands one field back to automation. array_remove is a no-op on a field that is not
// locked, so a double submit is harmless.
func (q *Queries) DashUnlockSongField(ctx context.Context, arg DashUnlockSongFieldParams) (Song, error) {
	row := q.db.QueryRow(ctx, dashUnlockSongField, arg.Field, arg.ID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const dashUpdateSong = `-- name: DashUpdateSong :one
UPDATE songs SET
    -- The ::varchar casts on name are load-bearing, the same way the ::text casts in
    -- UpdateSongWithStmpdRelease are. This parameter appears both as an assignment and
    -- inside the normalized_name CASE below, and without a cast Postgres tries to
    -- deduce a type for it twice and raises 42P08, "inconsistent types deduced for
    -- parameter $1".
    name = $1::varchar,
    artists = $2,
    mix_name = $3,
    thumbnail_url = $4,
    spotify_url = $5,
    apple_music_url = $6,
    youtube_url = $7,
    youtube_music_url = $8,
    deezer_url = $9,
    tidal_url = $10,
    amazon_music_url = $11,
    beatport_url = $12,
    release_date = $13::text,
    release_name = $14,
    lyrics = $15,
    genre = $16,
    sub_genre = $17,
    bpm = $18::int,
    musical_key = $19,
    is_collection = $20,
    is_instrumental = $21,
    is_unreleased = $22,
    -- Derived from name, so a hand-edited name invalidates it. Cleared rather than
    -- recomputed for the reason 000021 gives: SQL cannot derive it, and NULL means
    -- "derive on read", which is survivable where a stale stored value is not.
    normalized_name = CASE WHEN name IS DISTINCT FROM $1::varchar
                           THEN NULL ELSE normalized_name END,
    locked_fields = $23::text[]
WHERE id = $24
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text
`

type DashUpdateSongParams struct {
	Name            string      `json:"name"`
	Artists         string      `json:"artists"`
	MixName         pgtype.Text `json:"mixName"`
	ThumbnailUrl    pgtype.Text `json:"thumbnailUrl"`
	SpotifyUrl      pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl   pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl      pgtype.Text `json:"youtubeUrl"`
	YoutubeMusicUrl pgtype.Text `json:"youtubeMusicUrl"`
	DeezerUrl       pgtype.Text `json:"deezerUrl"`
	TidalUrl        pgtype.Text `json:"tidalUrl"`
	AmazonMusicUrl  pgtype.Text `json:"amazonMusicUrl"`
	BeatportUrl     pgtype.Text `json:"beatportUrl"`
	ReleaseDate     pgtype.Text `json:"releaseDate"`
	ReleaseName     pgtype.Text `json:"releaseName"`
	Lyrics          pgtype.Text `json:"lyrics"`
	Genre           pgtype.Text `json:"genre"`
	SubGenre        pgtype.Text `json:"subGenre"`
	Bpm             pgtype.Int4 `json:"bpm"`
	MusicalKey      pgtype.Text `json:"musicalKey"`
	IsCollection    bool        `json:"isCollection"`
	IsInstrumental  bool        `json:"isInstrumental"`
	IsUnreleased    bool        `json:"isUnreleased"`
	LockedFields    []string    `json:"lockedFields"`
	ID              int64       `json:"id"`
}

// Every editable column is submitted on every save, including the empty ones, so that
// clearing a field works -- the same contract UpdateGuildConfig has.
//
// locked_fields arrives already computed rather than being derived here. The handler
// has diffed the submitted values against the stored row to build the audit line
// anyway, so it already knows which columns changed; expressing "which of these twenty
// assignments changed something" in SQL would be a second, harder implementation of a
// question already answered.
//
// No lock guard on these assignments, unlike every automated writer: this IS the
// authority the locks exist to protect. A person looking at the row is the one writing.
func (q *Queries) DashUpdateSong(ctx context.Context, arg DashUpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, dashUpdateSong,
		arg.Name,
		arg.Artists,
		arg.MixName,
		arg.ThumbnailUrl,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.YoutubeMusicUrl,
		arg.DeezerUrl,
		arg.TidalUrl,
		arg.AmazonMusicUrl,
		arg.BeatportUrl,
		arg.ReleaseDate,
		arg.ReleaseName,
		arg.Lyrics,
		arg.Genre,
		arg.SubGenre,
		arg.Bpm,
		arg.MusicalKey,
		arg.IsCollection,
		arg.IsInstrumental,
		arg.IsUnreleased,
		arg.LockedFields,
		arg.ID,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}
