// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptSongIdentifiers = `-- name: AdoptSongIdentifiers :exec
UPDATE songs SET
    beatport_id = COALESCE(beatport_id, $1),
    stmpd_slug  = COALESCE(stmpd_slug,  $2)
WHERE id = $3
`

type AdoptSongIdentifiersParams struct {
	BeatportID pgtype.Int4 `json:"beatportId"`
	StmpdSlug  pgtype.Text `json:"stmpdSlug"`
	ID         int64       `json:"id"`
}

// Give the surviving row the identifiers released above, without overwriting any it
// already has of its own.
func (q *Queries) AdoptSongIdentifiers(ctx context.Context, arg AdoptSongIdentifiersParams) error {
	_, err := q.db.Exec(ctx, adoptSongIdentifiers, arg.BeatportID, arg.StmpdSlug, arg.ID)
	return err
}

const copyLyricsToRemixes = `-- name: CopyLyricsToRemixes :execrows
UPDATE songs t SET lyrics = s.lyrics
FROM songs s
WHERE s.id = $1 AND t.parent_song_id = s.id AND t.lyrics IS NULL
  AND s.lyrics IS NOT NULL AND NOT t.is_instrumental
`

// Lyrics are entered by hand against the canonical row. A remix of a vocal track has
// the same words, so fan them out rather than making someone paste them ten times.
func (q *Queries) CopyLyricsToRemixes(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, copyLyricsToRemixes, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLinklessSongs = `-- name: CountLinklessSongs :one
SELECT count(*) FROM songs
WHERE spotify_url IS NULL AND apple_music_url IS NULL AND youtube_url IS NULL
`

func (q *Queries) CountLinklessSongs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinklessSongs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const doesBeatportSongExist = `-- name: DoesBeatportSongExist :one
SELECT EXISTS(SELECT 1 FROM songs WHERE beatport_id = $1)
`

func (q *Queries) DoesBeatportSongExist(ctx context.Context, beatportID pgtype.Int4) (bool, error) {
	row := q.db.QueryRow(ctx, doesBeatportSongExist, beatportID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const doesSongExist = `-- name: DoesSongExist :one
SELECT EXISTS(SELECT 1 FROM songs WHERE name = $1 AND artists = $2 AND release_date = $3)
`

type DoesSongExistParams struct {
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) DoesSongExist(ctx context.Context, arg DoesSongExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, doesSongExist, arg.Name, arg.Artists, arg.ReleaseDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllSongsForMatching = `-- name: GetAllSongsForMatching :many
SELECT id, name, artists, source, beatport_id, beatport_release_id,
       stmpd_slug, match_key, base_key, mix_name, spotify_url, stmpd_synced_at
FROM songs
`

type GetAllSongsForMatchingRow struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Artists           string             `json:"artists"`
	Source            string             `json:"source"`
	BeatportID        pgtype.Int4        `json:"beatportId"`
	BeatportReleaseID pgtype.Int4        `json:"beatportReleaseId"`
	StmpdSlug         pgtype.Text        `json:"stmpdSlug"`
	MatchKey          pgtype.Text        `json:"matchKey"`
	BaseKey           pgtype.Text        `json:"baseKey"`
	MixName           pgtype.Text        `json:"mixName"`
	SpotifyUrl        pgtype.Text        `json:"spotifyUrl"`
	StmpdSyncedAt     pgtype.Timestamptz `json:"stmpdSyncedAt"`
}

func (q *Queries) GetAllSongsForMatching(ctx context.Context) ([]GetAllSongsForMatchingRow, error) {
	rows, err := q.db.Query(ctx, getAllSongsForMatching)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSongsForMatchingRow
	for rows.Next() {
		var i GetAllSongsForMatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.Source,
			&i.BeatportID,
			&i.BeatportReleaseID,
			&i.StmpdSlug,
			&i.MatchKey,
			&i.BaseKey,
			&i.MixName,
			&i.SpotifyUrl,
			&i.StmpdSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicateMatchKeyRows = `-- name: GetDuplicateMatchKeyRows :many
SELECT id, name, artists, mix_name, release_date, source, match_key,
       stmpd_slug, beatport_id, spotify_url, apple_music_url, youtube_url,
       lyrics, parent_song_id, thumbnail_url
FROM songs
WHERE match_key IN (
    SELECT match_key FROM songs
    WHERE match_key IS NOT NULL AND match_key <> '||'
    GROUP BY match_key HAVING count(*) > 1
)
ORDER BY match_key, id
`

type GetDuplicateMatchKeyRowsRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseDate   string      `json:"releaseDate"`
	Source        string      `json:"source"`
	MatchKey      pgtype.Text `json:"matchKey"`
	StmpdSlug     pgtype.Text `json:"stmpdSlug"`
	BeatportID    pgtype.Int4 `json:"beatportId"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	Lyrics        pgtype.Text `json:"lyrics"`
	ParentSongID  pgtype.Int8 `json:"parentSongId"`
	ThumbnailUrl  pgtype.Text `json:"thumbnailUrl"`
}

// Every row belonging to a match_key held by more than one row. A match_key is the
// artist set, the base title and the rendition, so two rows sharing one are the same
// recording stored twice -- usually once per source, with the variant in `name` on
// one side and in `mix_name` on the other.
func (q *Queries) GetDuplicateMatchKeyRows(ctx context.Context) ([]GetDuplicateMatchKeyRowsRow, error) {
	rows, err := q.db.Query(ctx, getDuplicateMatchKeyRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDuplicateMatchKeyRowsRow
	for rows.Next() {
		var i GetDuplicateMatchKeyRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.Source,
			&i.MatchKey,
			&i.StmpdSlug,
			&i.BeatportID,
			&i.SpotifyUrl,
			&i.AppleMusicUrl,
			&i.YoutubeUrl,
			&i.Lyrics,
			&i.ParentSongID,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSongForRadio = `-- name: GetRandomSongForRadio :one
SELECT id, name, artists, thumbnail_url, youtube_url
FROM songs
WHERE youtube_url IS NOT NULL
  AND parent_song_id IS NULL
  AND (length_ms IS NULL OR length_ms <= 600000)
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomSongForRadioRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	YoutubeUrl   pgtype.Text `json:"youtubeUrl"`
}

// Canonical rows only, so the rotation does not play six versions of one track.
func (q *Queries) GetRandomSongForRadio(ctx context.Context) (GetRandomSongForRadioRow, error) {
	row := q.db.QueryRow(ctx, getRandomSongForRadio)
	var i GetRandomSongForRadioRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.YoutubeUrl,
	)
	return i, err
}

const getRandomSongNames = `-- name: GetRandomSongNames :many
SELECT id, name, artists, release_date
FROM songs
WHERE parent_song_id IS NULL
ORDER BY RANDOM()
LIMIT 20
`

type GetRandomSongNamesRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) GetRandomSongNames(ctx context.Context) ([]GetRandomSongNamesRow, error) {
	rows, err := q.db.Query(ctx, getRandomSongNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomSongNamesRow
	for rows.Next() {
		var i GetRandomSongNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSongNamesWithLyrics = `-- name: GetRandomSongNamesWithLyrics :many
SELECT id, name, artists, release_date
FROM songs
WHERE lyrics IS NOT NULL AND parent_song_id IS NULL
ORDER BY RANDOM()
LIMIT 20
`

type GetRandomSongNamesWithLyricsRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) GetRandomSongNamesWithLyrics(ctx context.Context) ([]GetRandomSongNamesWithLyricsRow, error) {
	rows, err := q.db.Query(ctx, getRandomSongNamesWithLyrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomSongNamesWithLyricsRow
	for rows.Next() {
		var i GetRandomSongNamesWithLyricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSongWithLyrics = `-- name: GetRandomSongWithLyrics :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental FROM songs
WHERE lyrics IS NOT NULL
AND NOT is_instrumental
AND parent_song_id IS NULL
AND (LOWER(artists) LIKE '%martin garrix%'
   OR LOWER(artists) LIKE '%area21%'
   OR LOWER(artists) LIKE '%ytram%'
   OR LOWER(artists) LIKE '%grx%')
ORDER BY RANDOM()
LIMIT 1
`

// '%ytram%' was '%ytrram%'. The typo meant no Ytram song has ever been served by
// the quiz; config.toml's monitored-artist list confirms the correct spelling.
func (q *Queries) GetRandomSongWithLyrics(ctx context.Context) (Song, error) {
	row := q.db.QueryRow(ctx, getRandomSongWithLyrics)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const getRandomSongWithLyricsEasy = `-- name: GetRandomSongWithLyricsEasy :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental FROM songs
WHERE lyrics IS NOT NULL
AND NOT is_instrumental
AND parent_song_id IS NULL
AND LOWER(artists) LIKE '%martin garrix%'
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomSongWithLyricsEasy(ctx context.Context) (Song, error) {
	row := q.db.QueryRow(ctx, getRandomSongWithLyricsEasy)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const getSong = `-- name: GetSong :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental FROM songs WHERE name = $1 AND artists = $2 AND release_date = $3
`

type GetSongParams struct {
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) GetSong(ctx context.Context, arg GetSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, getSong, arg.Name, arg.Artists, arg.ReleaseDate)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const getSongByBeatportID = `-- name: GetSongByBeatportID :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental FROM songs WHERE beatport_id = $1
`

func (q *Queries) GetSongByBeatportID(ctx context.Context, beatportID pgtype.Int4) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByBeatportID, beatportID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const getSongByStmpdSlug = `-- name: GetSongByStmpdSlug :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental FROM songs WHERE stmpd_slug = $1
`

func (q *Queries) GetSongByStmpdSlug(ctx context.Context, stmpdSlug pgtype.Text) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByStmpdSlug, stmpdSlug)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const getSongMixes = `-- name: GetSongMixes :many
SELECT id, name, mix_name, artists FROM songs
WHERE parent_song_id = $1 ORDER BY release_date, id
`

type GetSongMixesRow struct {
	ID      int64       `json:"id"`
	Name    string      `json:"name"`
	MixName pgtype.Text `json:"mixName"`
	Artists string      `json:"artists"`
}

// The renditions hanging off a canonical song, for the track card to list.
func (q *Queries) GetSongMixes(ctx context.Context, parentSongID pgtype.Int8) ([]GetSongMixesRow, error) {
	rows, err := q.db.Query(ctx, getSongMixes, parentSongID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongMixesRow
	for rows.Next() {
		var i GetSongMixesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MixName,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsForKeying = `-- name: GetSongsForKeying :many
SELECT id, name, artists, mix_name FROM songs ORDER BY id
`

type GetSongsForKeyingRow struct {
	ID      int64       `json:"id"`
	Name    string      `json:"name"`
	Artists string      `json:"artists"`
	MixName pgtype.Text `json:"mixName"`
}

func (q *Queries) GetSongsForKeying(ctx context.Context) ([]GetSongsForKeyingRow, error) {
	rows, err := q.db.Query(ctx, getSongsForKeying)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsForKeyingRow
	for rows.Next() {
		var i GetSongsForKeyingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsForParentLinking = `-- name: GetSongsForParentLinking :many
SELECT id, name, artists, mix_name, release_date, source, base_key,
       spotify_url, youtube_url, apple_music_url, lyrics, parent_song_id
FROM songs ORDER BY id
`

type GetSongsForParentLinkingRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseDate   string      `json:"releaseDate"`
	Source        string      `json:"source"`
	BaseKey       pgtype.Text `json:"baseKey"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	Lyrics        pgtype.Text `json:"lyrics"`
	ParentSongID  pgtype.Int8 `json:"parentSongId"`
}

func (q *Queries) GetSongsForParentLinking(ctx context.Context) ([]GetSongsForParentLinkingRow, error) {
	rows, err := q.db.Query(ctx, getSongsForParentLinking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsForParentLinkingRow
	for rows.Next() {
		var i GetSongsForParentLinkingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.Source,
			&i.BaseKey,
			&i.SpotifyUrl,
			&i.YoutubeUrl,
			&i.AppleMusicUrl,
			&i.Lyrics,
			&i.ParentSongID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsLike = `-- name: GetSongsLike :many
SELECT id, name, artists, release_date
FROM songs
WHERE parent_song_id IS NULL
  AND LOWER(artists || ' - ' || name) LIKE LOWER($1)
ORDER BY release_date DESC
LIMIT 20
`

type GetSongsLikeRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

// Autocomplete offers one entry per song. Remix rows are excluded: ten "Told You
// So" choices is not a useful list, and the choice payload is capped at 100 bytes
// by Discord, which long remix names were overflowing.
func (q *Queries) GetSongsLike(ctx context.Context, lower string) ([]GetSongsLikeRow, error) {
	rows, err := q.db.Query(ctx, getSongsLike, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsLikeRow
	for rows.Next() {
		var i GetSongsLikeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsMissingLinks = `-- name: GetSongsMissingLinks :many
SELECT id, name, artists, release_date, source, beatport_id
FROM songs WHERE stmpd_synced_at IS NULL ORDER BY id
`

type GetSongsMissingLinksRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	ReleaseDate string      `json:"releaseDate"`
	Source      string      `json:"source"`
	BeatportID  pgtype.Int4 `json:"beatportId"`
}

// The backfill queue: rows the STMPD sync has never successfully applied to. After
// migration 000009 this is exactly the set of rows carrying no streaming links.
func (q *Queries) GetSongsMissingLinks(ctx context.Context) ([]GetSongsMissingLinksRow, error) {
	rows, err := q.db.Query(ctx, getSongsMissingLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsMissingLinksRow
	for rows.Next() {
		var i GetSongsMissingLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
			&i.Source,
			&i.BeatportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsNeverAnnounced = `-- name: GetSongsNeverAnnounced :many
SELECT id, name, artists, release_date FROM songs WHERE announced_at IS NULL
`

type GetSongsNeverAnnouncedRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) GetSongsNeverAnnounced(ctx context.Context) ([]GetSongsNeverAnnouncedRow, error) {
	rows, err := q.db.Query(ctx, getSongsNeverAnnounced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsNeverAnnouncedRow
	for rows.Next() {
		var i GetSongsNeverAnnouncedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithLyricsLike = `-- name: GetSongsWithLyricsLike :many
SELECT id, name, artists, release_date
FROM songs
WHERE lyrics IS NOT NULL
  AND parent_song_id IS NULL
  AND LOWER(artists || ' - ' || name) LIKE LOWER($1)
ORDER BY release_date DESC
LIMIT 20
`

type GetSongsWithLyricsLikeRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Artists     string `json:"artists"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) GetSongsWithLyricsLike(ctx context.Context, lower string) ([]GetSongsWithLyricsLikeRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithLyricsLike, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithLyricsLikeRow
	for rows.Next() {
		var i GetSongsWithLyricsLikeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithPlaceholderDate = `-- name: GetSongsWithPlaceholderDate :many
SELECT id, name, artists, release_date, apple_music_url, spotify_url
FROM songs WHERE release_date = '1970-01-01'
ORDER BY (apple_music_url IS NULL), id
`

type GetSongsWithPlaceholderDateRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	ReleaseDate   string      `json:"releaseDate"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
}

// Legacy rows carrying the 1970-01-01 sentinel the old importer wrote when it had no
// date. Ordered so the ones we can actually resolve come first.
func (q *Queries) GetSongsWithPlaceholderDate(ctx context.Context) ([]GetSongsWithPlaceholderDateRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithPlaceholderDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithPlaceholderDateRow
	for rows.Next() {
		var i GetSongsWithPlaceholderDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
			&i.AppleMusicUrl,
			&i.SpotifyUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBeatportSong = `-- name: InsertBeatportSong :one
INSERT INTO songs (
    name, artists, release_date, thumbnail_url, beatport_id, mix_name,
    release_name, genre, sub_genre, bpm, musical_key, length_ms, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'beatport')
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental
`

type InsertBeatportSongParams struct {
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	ReleaseDate  string      `json:"releaseDate"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	BeatportID   pgtype.Int4 `json:"beatportId"`
	MixName      pgtype.Text `json:"mixName"`
	ReleaseName  pgtype.Text `json:"releaseName"`
	Genre        pgtype.Text `json:"genre"`
	SubGenre     pgtype.Text `json:"subGenre"`
	Bpm          pgtype.Int4 `json:"bpm"`
	MusicalKey   pgtype.Text `json:"musicalKey"`
	LengthMs     pgtype.Int4 `json:"lengthMs"`
}

func (q *Queries) InsertBeatportSong(ctx context.Context, arg InsertBeatportSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, insertBeatportSong,
		arg.Name,
		arg.Artists,
		arg.ReleaseDate,
		arg.ThumbnailUrl,
		arg.BeatportID,
		arg.MixName,
		arg.ReleaseName,
		arg.Genre,
		arg.SubGenre,
		arg.Bpm,
		arg.MusicalKey,
		arg.LengthMs,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO songs (
    name, artists, release_date, thumbnail_url, stmpd_slug,
    spotify_url, apple_music_url, youtube_url, youtube_music_url,
    deezer_url, tidal_url, amazon_music_url, beatport_url, beatport_release_id,
    stmpd_synced_at, source
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14,
    NOW(), 'stmpd'
)
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental
`

type InsertReleaseParams struct {
	Name              string      `json:"name"`
	Artists           string      `json:"artists"`
	ReleaseDate       string      `json:"releaseDate"`
	ThumbnailUrl      pgtype.Text `json:"thumbnailUrl"`
	StmpdSlug         pgtype.Text `json:"stmpdSlug"`
	SpotifyUrl        pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl     pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl        pgtype.Text `json:"youtubeUrl"`
	YoutubeMusicUrl   pgtype.Text `json:"youtubeMusicUrl"`
	DeezerUrl         pgtype.Text `json:"deezerUrl"`
	TidalUrl          pgtype.Text `json:"tidalUrl"`
	AmazonMusicUrl    pgtype.Text `json:"amazonMusicUrl"`
	BeatportUrl       pgtype.Text `json:"beatportUrl"`
	BeatportReleaseID pgtype.Int4 `json:"beatportReleaseId"`
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (Song, error) {
	row := q.db.QueryRow(ctx, insertRelease,
		arg.Name,
		arg.Artists,
		arg.ReleaseDate,
		arg.ThumbnailUrl,
		arg.StmpdSlug,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.YoutubeMusicUrl,
		arg.DeezerUrl,
		arg.TidalUrl,
		arg.AmazonMusicUrl,
		arg.BeatportUrl,
		arg.BeatportReleaseID,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
	)
	return i, err
}

const markBeatportUpdated = `-- name: MarkBeatportUpdated :exec
UPDATE songs SET beatport_updated = TRUE WHERE id = $1
`

func (q *Queries) MarkBeatportUpdated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markBeatportUpdated, id)
	return err
}

const markSongAnnounced = `-- name: MarkSongAnnounced :exec
UPDATE songs SET announced_at = NOW() WHERE id = $1 AND announced_at IS NULL
`

func (q *Queries) MarkSongAnnounced(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSongAnnounced, id)
	return err
}

const mergeSongRows = `-- name: MergeSongRows :exec
UPDATE songs w SET
    spotify_url     = COALESCE(w.spotify_url,     l.spotify_url),
    apple_music_url = COALESCE(w.apple_music_url, l.apple_music_url),
    youtube_url     = COALESCE(w.youtube_url,     l.youtube_url),
    thumbnail_url   = COALESCE(NULLIF(w.thumbnail_url, ''), l.thumbnail_url),
    lyrics          = COALESCE(w.lyrics,          l.lyrics),
    bpm             = COALESCE(w.bpm,             l.bpm),
    musical_key     = COALESCE(w.musical_key,     l.musical_key),
    length_ms       = COALESCE(w.length_ms,       l.length_ms),
    genre           = COALESCE(w.genre,           l.genre),
    sub_genre       = COALESCE(w.sub_genre,       l.sub_genre),
    mix_name        = COALESCE(w.mix_name,        l.mix_name),
    release_name    = COALESCE(w.release_name,    l.release_name),
    -- The columns below were added after this query was first written. Leaving them
    -- out silently discarded the loser's slug and its deezer/tidal/amazon links.
    -- beatport_id and stmpd_slug are handled by Release/AdoptSongIdentifiers:
    -- both are uniquely indexed and cannot be copied while the loser still holds them.
    youtube_music_url   = COALESCE(w.youtube_music_url,   l.youtube_music_url),
    deezer_url          = COALESCE(w.deezer_url,          l.deezer_url),
    tidal_url           = COALESCE(w.tidal_url,           l.tidal_url),
    amazon_music_url    = COALESCE(w.amazon_music_url,    l.amazon_music_url),
    beatport_url        = COALESCE(w.beatport_url,        l.beatport_url),
    beatport_release_id = COALESCE(w.beatport_release_id, l.beatport_release_id),
    -- A real date always beats the 1970-01-01 placeholder, whichever row holds it.
    release_date    = CASE WHEN w.release_date = '1970-01-01' AND l.release_date <> '1970-01-01'
                           THEN l.release_date ELSE w.release_date END,
    announced_at    = LEAST(w.announced_at,       l.announced_at),
    first_seen_at   = LEAST(w.first_seen_at,      l.first_seen_at),
    stmpd_synced_at = COALESCE(w.stmpd_synced_at, l.stmpd_synced_at),
    beatport_updated = w.beatport_updated OR l.beatport_updated
FROM songs l
WHERE w.id = $1 AND l.id = $2
`

type MergeSongRowsParams struct {
	WinnerID int64 `json:"winnerId"`
	LoserID  int64 `json:"loserId"`
}

// Fold `loser` into `winner`, keeping the first non-null of each field. Used when a
// release_date correction would collide with the unique_release constraint: the
// collision means a twin row already holds that identity, so the two are the same
// song arriving from two sources. Nothing has a foreign key to songs, so the loser
// can be deleted afterwards.
func (q *Queries) MergeSongRows(ctx context.Context, arg MergeSongRowsParams) error {
	_, err := q.db.Exec(ctx, mergeSongRows, arg.WinnerID, arg.LoserID)
	return err
}

const releaseSongIdentifiers = `-- name: ReleaseSongIdentifiers :exec
UPDATE songs SET beatport_id = NULL, stmpd_slug = NULL WHERE id = $1
`

// Clear the uniquely-indexed identifiers from a row that is about to be merged away.
//
// beatport_id and stmpd_slug each carry a partial unique index, so copying them onto
// the surviving row while this one still holds them violates the index. The caller
// captured the values first and reassigns them with AdoptSongIdentifiers once this
// row no longer claims them.
func (q *Queries) ReleaseSongIdentifiers(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseSongIdentifiers, id)
	return err
}

const repointChildren = `-- name: RepointChildren :execrows
UPDATE songs SET parent_song_id = $1
WHERE parent_song_id = $2
`

type RepointChildrenParams struct {
	NewParent pgtype.Int8 `json:"newParent"`
	OldParent pgtype.Int8 `json:"oldParent"`
}

// Move a merged-away row's remixes onto the row that survives.
func (q *Queries) RepointChildren(ctx context.Context, arg RepointChildrenParams) (int64, error) {
	result, err := q.db.Exec(ctx, repointChildren, arg.NewParent, arg.OldParent)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongInstrumental = `-- name: SetSongInstrumental :execrows
UPDATE songs SET is_instrumental = $2 WHERE id = $1 AND is_instrumental IS DISTINCT FROM $2
`

type SetSongInstrumentalParams struct {
	ID             int64 `json:"id"`
	IsInstrumental bool  `json:"isInstrumental"`
}

func (q *Queries) SetSongInstrumental(ctx context.Context, arg SetSongInstrumentalParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongInstrumental, arg.ID, arg.IsInstrumental)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongKeys = `-- name: SetSongKeys :execrows
UPDATE songs SET match_key = $2, base_key = $3
WHERE id = $1 AND (match_key IS DISTINCT FROM $2 OR base_key IS DISTINCT FROM $3)
`

type SetSongKeysParams struct {
	ID       int64       `json:"id"`
	MatchKey pgtype.Text `json:"matchKey"`
	BaseKey  pgtype.Text `json:"baseKey"`
}

func (q *Queries) SetSongKeys(ctx context.Context, arg SetSongKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongKeys, arg.ID, arg.MatchKey, arg.BaseKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongParent = `-- name: SetSongParent :execrows
UPDATE songs SET parent_song_id = $1
WHERE id = $2 AND parent_song_id IS DISTINCT FROM $1
`

type SetSongParentParams struct {
	ParentSongID pgtype.Int8 `json:"parentSongId"`
	ID           int64       `json:"id"`
}

func (q *Queries) SetSongParent(ctx context.Context, arg SetSongParentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongParent, arg.ParentSongID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongReleaseDate = `-- name: SetSongReleaseDate :execrows
UPDATE songs SET release_date = $2 WHERE id = $1 AND release_date IS DISTINCT FROM $2
`

type SetSongReleaseDateParams struct {
	ID          int64  `json:"id"`
	ReleaseDate string `json:"releaseDate"`
}

func (q *Queries) SetSongReleaseDate(ctx context.Context, arg SetSongReleaseDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongReleaseDate, arg.ID, arg.ReleaseDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongWithBeatportData = `-- name: UpdateSongWithBeatportData :execrows
UPDATE songs SET
    name          = $1,
    artists       = $2,
    thumbnail_url = COALESCE($3, thumbnail_url),
    beatport_id   = $4,
    mix_name      = $5,
    release_date  = $6,
    release_name  = $7,
    genre         = $8,
    sub_genre     = $9,
    bpm           = $10,
    musical_key   = $11,
    length_ms     = $12,
    beatport_updated = TRUE
WHERE id = $13
  AND (
       name          IS DISTINCT FROM $1
    OR artists       IS DISTINCT FROM $2
    OR thumbnail_url IS DISTINCT FROM COALESCE($3, thumbnail_url)
    OR beatport_id   IS DISTINCT FROM $4
    OR mix_name      IS DISTINCT FROM $5
    OR release_date  IS DISTINCT FROM $6
    OR release_name  IS DISTINCT FROM $7
    OR genre         IS DISTINCT FROM $8
    OR sub_genre     IS DISTINCT FROM $9
    OR bpm           IS DISTINCT FROM $10
    OR musical_key   IS DISTINCT FROM $11
    OR length_ms     IS DISTINCT FROM $12
    OR beatport_updated IS DISTINCT FROM TRUE
  )
`

type UpdateSongWithBeatportDataParams struct {
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	BeatportID   pgtype.Int4 `json:"beatportId"`
	MixName      pgtype.Text `json:"mixName"`
	ReleaseDate  string      `json:"releaseDate"`
	ReleaseName  pgtype.Text `json:"releaseName"`
	Genre        pgtype.Text `json:"genre"`
	SubGenre     pgtype.Text `json:"subGenre"`
	Bpm          pgtype.Int4 `json:"bpm"`
	MusicalKey   pgtype.Text `json:"musicalKey"`
	LengthMs     pgtype.Int4 `json:"lengthMs"`
	ID           int64       `json:"id"`
}

// :execrows plus the IS DISTINCT FROM guard below make this a no-op when the row
// already holds this data. Without it every cycle rewrote the same ~73 rows and
// reported updated=73 forever, which hid whether anything had actually changed.
// thumbnail_url is COALESCEd rather than assigned: a beatport track with no square
// artwork arrives as NULL and must not erase artwork another source already found.
func (q *Queries) UpdateSongWithBeatportData(ctx context.Context, arg UpdateSongWithBeatportDataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSongWithBeatportData,
		arg.Name,
		arg.Artists,
		arg.ThumbnailUrl,
		arg.BeatportID,
		arg.MixName,
		arg.ReleaseDate,
		arg.ReleaseName,
		arg.Genre,
		arg.SubGenre,
		arg.Bpm,
		arg.MusicalKey,
		arg.LengthMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongWithStmpdLinks = `-- name: UpdateSongWithStmpdLinks :execrows
UPDATE songs SET
    spotify_url     = COALESCE($1,     spotify_url),
    apple_music_url = COALESCE($2, apple_music_url),
    youtube_url     = COALESCE($3,     youtube_url),
    thumbnail_url   = CASE WHEN thumbnail_url IS NULL OR thumbnail_url = ''
                           THEN $4 ELSE thumbnail_url END,
    stmpd_synced_at = NOW()
WHERE id = $5
  AND (
       spotify_url     IS DISTINCT FROM COALESCE($1,     spotify_url)
    OR apple_music_url IS DISTINCT FROM COALESCE($2, apple_music_url)
    OR youtube_url     IS DISTINCT FROM COALESCE($3,     youtube_url)
    -- Only a reason to write when there is actually a thumbnail to write. Testing
    -- emptiness alone would match forever on a row neither side has artwork for,
    -- re-stamping it every cycle and reintroducing the churn this guard removes.
    --
    -- The cast is required, not cosmetic: IS NOT NULL accepts any type, so this is
    -- the one place the parameter appears without a type to infer from, and Postgres
    -- rejects the whole statement with 42P08 at execution time.
    OR (COALESCE(thumbnail_url, '') = '' AND $4::text IS NOT NULL)
    OR stmpd_synced_at IS NULL
  )
`

type UpdateSongWithStmpdLinksParams struct {
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	ThumbnailUrl  pgtype.Text `json:"thumbnailUrl"`
	ID            int64       `json:"id"`
}

// This no longer touches beatport_updated. That flag is the beatport fetcher's own
// "already enriched, skip" sentinel; setting it here made the STMPD backfill skip
// every row beatport had ever touched, which is why 497 beatport rows had no links.
// stmpd_synced_at is this fetcher's separate record of having visited the row.
func (q *Queries) UpdateSongWithStmpdLinks(ctx context.Context, arg UpdateSongWithStmpdLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSongWithStmpdLinks,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.ThumbnailUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongWithStmpdRelease = `-- name: UpdateSongWithStmpdRelease :execrows
UPDATE songs SET
    stmpd_slug          = COALESCE($1,          stmpd_slug),
    release_date        = COALESCE($2,        release_date),
    spotify_url         = COALESCE($3,         spotify_url),
    apple_music_url     = COALESCE($4,     apple_music_url),
    youtube_url         = COALESCE($5,         youtube_url),
    youtube_music_url   = COALESCE($6,   youtube_music_url),
    deezer_url          = COALESCE($7,          deezer_url),
    tidal_url           = COALESCE($8,           tidal_url),
    amazon_music_url    = COALESCE($9,    amazon_music_url),
    beatport_url        = COALESCE($10,        beatport_url),
    beatport_release_id = COALESCE($11, beatport_release_id),
    thumbnail_url       = CASE WHEN COALESCE(thumbnail_url, '') = ''
                               THEN $12 ELSE thumbnail_url END,
    stmpd_synced_at     = NOW()
WHERE id = $13
  AND (
       stmpd_slug          IS DISTINCT FROM COALESCE($1,          stmpd_slug)
    OR release_date        IS DISTINCT FROM COALESCE($2,        release_date)
    OR spotify_url         IS DISTINCT FROM COALESCE($3,         spotify_url)
    OR apple_music_url     IS DISTINCT FROM COALESCE($4,     apple_music_url)
    OR youtube_url         IS DISTINCT FROM COALESCE($5,         youtube_url)
    OR youtube_music_url   IS DISTINCT FROM COALESCE($6,   youtube_music_url)
    OR deezer_url          IS DISTINCT FROM COALESCE($7,          deezer_url)
    OR tidal_url           IS DISTINCT FROM COALESCE($8,           tidal_url)
    OR amazon_music_url    IS DISTINCT FROM COALESCE($9,    amazon_music_url)
    OR beatport_url        IS DISTINCT FROM COALESCE($10,        beatport_url)
    OR beatport_release_id IS DISTINCT FROM COALESCE($11, beatport_release_id)
    -- Cast for the same reason as in UpdateSongWithStmpdLinks: IS NOT NULL leaves
    -- the parameter's type undetermined and Postgres raises 42P08.
    OR (COALESCE(thumbnail_url, '') = '' AND $12::text IS NOT NULL)
    OR stmpd_synced_at IS NULL
  )
`

type UpdateSongWithStmpdReleaseParams struct {
	StmpdSlug         pgtype.Text `json:"stmpdSlug"`
	ReleaseDate       pgtype.Text `json:"releaseDate"`
	SpotifyUrl        pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl     pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl        pgtype.Text `json:"youtubeUrl"`
	YoutubeMusicUrl   pgtype.Text `json:"youtubeMusicUrl"`
	DeezerUrl         pgtype.Text `json:"deezerUrl"`
	TidalUrl          pgtype.Text `json:"tidalUrl"`
	AmazonMusicUrl    pgtype.Text `json:"amazonMusicUrl"`
	BeatportUrl       pgtype.Text `json:"beatportUrl"`
	BeatportReleaseID pgtype.Int4 `json:"beatportReleaseId"`
	ThumbnailUrl      pgtype.Text `json:"thumbnailUrl"`
	ID                int64       `json:"id"`
}

// The full-fidelity counterpart to UpdateSongWithStmpdLinks: everything the STMPD
// dataset knows about a release, applied to a row that already exists.
//
// release_date is COALESCEd rather than left alone because the dataset carries the
// exact date and many stored rows carry a "<year>-01-01" placeholder. Correcting it
// is safe now only because announcement is gated on songs.announced_at, which every
// pre-existing row already has stamped -- without that watermark this UPDATE would
// make the back catalogue look new.
//
// thumbnail_url is only ever filled in, never overwritten: roughly 800 of the 1015
// releases have no artwork in the dataset, and an empty value there means "unknown",
// not "this release has none".
func (q *Queries) UpdateSongWithStmpdRelease(ctx context.Context, arg UpdateSongWithStmpdReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSongWithStmpdRelease,
		arg.StmpdSlug,
		arg.ReleaseDate,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.YoutubeMusicUrl,
		arg.DeezerUrl,
		arg.TidalUrl,
		arg.AmazonMusicUrl,
		arg.BeatportUrl,
		arg.BeatportReleaseID,
		arg.ThumbnailUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
