// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tour_shows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const doesTourShowExist = `-- name: DoesTourShowExist :one
SELECT EXISTS(SELECT 1 FROM tour_shows WHERE show_name = $1 AND show_date = $2 AND venue = $3)
`

type DoesTourShowExistParams struct {
	ShowName string      `json:"showName"`
	ShowDate pgtype.Date `json:"showDate"`
	Venue    string      `json:"venue"`
}

func (q *Queries) DoesTourShowExist(ctx context.Context, arg DoesTourShowExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, doesTourShowExist, arg.ShowName, arg.ShowDate, arg.Venue)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllTourShows = `-- name: GetAllTourShows :many
SELECT id, show_name, city, country, venue, show_date, ticket_url, created_at FROM tour_shows ORDER BY show_date ASC
`

func (q *Queries) GetAllTourShows(ctx context.Context) ([]TourShow, error) {
	rows, err := q.db.Query(ctx, getAllTourShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TourShow
	for rows.Next() {
		var i TourShow
		if err := rows.Scan(
			&i.ID,
			&i.ShowName,
			&i.City,
			&i.Country,
			&i.Venue,
			&i.ShowDate,
			&i.TicketUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourNotificationChannels = `-- name: GetTourNotificationChannels :many
SELECT tour_notifications_channel, tour_notifications_role 
FROM guilds
WHERE tour_notifications_channel IS NOT NULL
`

type GetTourNotificationChannelsRow struct {
	TourNotificationsChannel pgtype.Int8 `json:"tourNotificationsChannel"`
	TourNotificationsRole    pgtype.Int8 `json:"tourNotificationsRole"`
}

func (q *Queries) GetTourNotificationChannels(ctx context.Context) ([]GetTourNotificationChannelsRow, error) {
	rows, err := q.db.Query(ctx, getTourNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTourNotificationChannelsRow
	for rows.Next() {
		var i GetTourNotificationChannelsRow
		if err := rows.Scan(&i.TourNotificationsChannel, &i.TourNotificationsRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTourShow = `-- name: InsertTourShow :one
INSERT INTO tour_shows (show_name, city, country, venue, show_date, ticket_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, show_name, city, country, venue, show_date, ticket_url, created_at
`

type InsertTourShowParams struct {
	ShowName  string      `json:"showName"`
	City      string      `json:"city"`
	Country   string      `json:"country"`
	Venue     string      `json:"venue"`
	ShowDate  pgtype.Date `json:"showDate"`
	TicketUrl pgtype.Text `json:"ticketUrl"`
}

func (q *Queries) InsertTourShow(ctx context.Context, arg InsertTourShowParams) (TourShow, error) {
	row := q.db.QueryRow(ctx, insertTourShow,
		arg.ShowName,
		arg.City,
		arg.Country,
		arg.Venue,
		arg.ShowDate,
		arg.TicketUrl,
	)
	var i TourShow
	err := row.Scan(
		&i.ID,
		&i.ShowName,
		&i.City,
		&i.Country,
		&i.Venue,
		&i.ShowDate,
		&i.TicketUrl,
		&i.CreatedAt,
	)
	return i, err
}
