// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCoins = `-- name: AddCoins :exec
UPDATE users SET in_hand=in_hand + $2 WHERE id = $1
`

type AddCoinsParams struct {
	ID     int64       `json:"id"`
	InHand pgtype.Int8 `json:"inHand"`
}

func (q *Queries) AddCoins(ctx context.Context, arg AddCoinsParams) error {
	_, err := q.db.Exec(ctx, addCoins, arg.ID, arg.InHand)
	return err
}

const depositAmount = `-- name: DepositAmount :exec
UPDATE users SET in_hand = in_hand - $2, garrix_coins = garrix_coins + $2 WHERE id = $1
`

type DepositAmountParams struct {
	ID     int64       `json:"id"`
	InHand pgtype.Int8 `json:"inHand"`
}

func (q *Queries) DepositAmount(ctx context.Context, arg DepositAmountParams) error {
	_, err := q.db.Exec(ctx, depositAmount, arg.ID, arg.InHand)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT garrix_coins, in_hand FROM users WHERE id = $1
`

type GetBalanceRow struct {
	GarrixCoins pgtype.Int8 `json:"garrixCoins"`
	InHand      pgtype.Int8 `json:"inHand"`
}

func (q *Queries) GetBalance(ctx context.Context, id int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, id)
	var i GetBalanceRow
	err := row.Scan(&i.GarrixCoins, &i.InHand)
	return i, err
}

const updateCoins = `-- name: UpdateCoins :exec
UPDATE users SET in_hand=$2 WHERE id = $1
`

type UpdateCoinsParams struct {
	ID     int64       `json:"id"`
	InHand pgtype.Int8 `json:"inHand"`
}

func (q *Queries) UpdateCoins(ctx context.Context, arg UpdateCoinsParams) error {
	_, err := q.db.Exec(ctx, updateCoins, arg.ID, arg.InHand)
	return err
}

const withdrawAmount = `-- name: WithdrawAmount :exec
UPDATE users SET in_hand = in_hand + $2, garrix_coins = garrix_coins - $2 WHERE id = $1
`

type WithdrawAmountParams struct {
	ID     int64       `json:"id"`
	InHand pgtype.Int8 `json:"inHand"`
}

func (q *Queries) WithdrawAmount(ctx context.Context, arg WithdrawAmountParams) error {
	_, err := q.db.Exec(ctx, withdrawAmount, arg.ID, arg.InHand)
	return err
}
