// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, guild_id)
VALUES ($1, $2)
RETURNING id, messages_sent, total_xp, last_xp_added, stmpd_coins, in_hand, guild_id
`

type CreateUserParams struct {
	ID      int64 `json:"id"`
	GuildID int64 `json:"guildId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.GuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MessagesSent,
		&i.TotalXp,
		&i.LastXpAdded,
		&i.StmpdCoins,
		&i.InHand,
		&i.GuildID,
	)
	return i, err
}

const getCoinsLeaderboard = `-- name: GetCoinsLeaderboard :many

SELECT id, stmpd_coins, in_hand FROM users
WHERE guild_id = $1
ORDER BY stmpd_coins + in_hand DESC NULLS LAST, id
OFFSET $2 LIMIT $3
`

type GetCoinsLeaderboardParams struct {
	GuildID int64 `json:"guildId"`
	Offset  int32 `json:"offset"`
	Limit   int32 `json:"limit"`
}

type GetCoinsLeaderboardRow struct {
	ID         int64 `json:"id"`
	StmpdCoins int64 `json:"stmpdCoins"`
	InHand     int64 `json:"inHand"`
}

// The four leaderboards below back /leaderboard. Two things they all need:
//
//	NULLS LAST -- migration 000025 made these columns NOT NULL, so nothing can
//	sort NULL-first any more, but saying it here means a future nullable column
//	cannot quietly reintroduce the bug that put ten zero-XP members at the top
//	of the levels board.
//
//	a trailing `id` -- a deterministic tiebreak. Without it members tied on the
//	same value swap places between queries, so paging past the first page can
//	repeat or skip rows.
func (q *Queries) GetCoinsLeaderboard(ctx context.Context, arg GetCoinsLeaderboardParams) ([]GetCoinsLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getCoinsLeaderboard, arg.GuildID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoinsLeaderboardRow
	for rows.Next() {
		var i GetCoinsLeaderboardRow
		if err := rows.Scan(&i.ID, &i.StmpdCoins, &i.InHand); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInHandLeaderboard = `-- name: GetInHandLeaderboard :many
SELECT id, in_hand FROM users
WHERE guild_id = $1
ORDER BY in_hand DESC NULLS LAST, id
OFFSET $2 LIMIT $3
`

type GetInHandLeaderboardParams struct {
	GuildID int64 `json:"guildId"`
	Offset  int32 `json:"offset"`
	Limit   int32 `json:"limit"`
}

type GetInHandLeaderboardRow struct {
	ID     int64 `json:"id"`
	InHand int64 `json:"inHand"`
}

func (q *Queries) GetInHandLeaderboard(ctx context.Context, arg GetInHandLeaderboardParams) ([]GetInHandLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getInHandLeaderboard, arg.GuildID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInHandLeaderboardRow
	for rows.Next() {
		var i GetInHandLeaderboardRow
		if err := rows.Scan(&i.ID, &i.InHand); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardCount = `-- name: GetLeaderboardCount :one
SELECT COUNT(*)::bigint FROM users WHERE guild_id = $1
`

// Total rows behind any of the leaderboards above, for the page count.
func (q *Queries) GetLeaderboardCount(ctx context.Context, guildID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLeaderboardCount, guildID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLevelsLeaderboard = `-- name: GetLevelsLeaderboard :many
SELECT id, total_xp FROM users
WHERE guild_id = $1
ORDER BY total_xp DESC NULLS LAST, id
OFFSET $2 LIMIT $3
`

type GetLevelsLeaderboardParams struct {
	GuildID int64 `json:"guildId"`
	Offset  int32 `json:"offset"`
	Limit   int32 `json:"limit"`
}

type GetLevelsLeaderboardRow struct {
	ID      int64 `json:"id"`
	TotalXp int32 `json:"totalXp"`
}

func (q *Queries) GetLevelsLeaderboard(ctx context.Context, arg GetLevelsLeaderboardParams) ([]GetLevelsLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLevelsLeaderboard, arg.GuildID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLevelsLeaderboardRow
	for rows.Next() {
		var i GetLevelsLeaderboardRow
		if err := rows.Scan(&i.ID, &i.TotalXp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesSentLeaderboard = `-- name: GetMessagesSentLeaderboard :many
SELECT id, messages_sent FROM users
WHERE guild_id = $1
ORDER BY messages_sent DESC NULLS LAST, id
OFFSET $2 LIMIT $3
`

type GetMessagesSentLeaderboardParams struct {
	GuildID int64 `json:"guildId"`
	Offset  int32 `json:"offset"`
	Limit   int32 `json:"limit"`
}

type GetMessagesSentLeaderboardRow struct {
	ID           int64 `json:"id"`
	MessagesSent int32 `json:"messagesSent"`
}

func (q *Queries) GetMessagesSentLeaderboard(ctx context.Context, arg GetMessagesSentLeaderboardParams) ([]GetMessagesSentLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getMessagesSentLeaderboard, arg.GuildID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesSentLeaderboardRow
	for rows.Next() {
		var i GetMessagesSentLeaderboardRow
		if err := rows.Scan(&i.ID, &i.MessagesSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, messages_sent, total_xp, last_xp_added, stmpd_coins, in_hand, guild_id FROM users WHERE id = $1 AND guild_id = $2
`

type GetUserParams struct {
	ID      int64 `json:"id"`
	GuildID int64 `json:"guildId"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.GuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MessagesSent,
		&i.TotalXp,
		&i.LastXpAdded,
		&i.StmpdCoins,
		&i.InHand,
		&i.GuildID,
	)
	return i, err
}

const getUserLevelData = `-- name: GetUserLevelData :one
WITH user_ranks AS (
  SELECT id, messages_sent, total_xp, last_xp_added, stmpd_coins, in_hand, guild_id,
         RANK() OVER (PARTITION BY guild_id ORDER BY total_xp DESC NULLS LAST) as rank
  FROM users
  WHERE guild_id = $2
)
SELECT id, messages_sent, total_xp, last_xp_added, stmpd_coins, in_hand, guild_id, rank
FROM user_ranks
WHERE id = $1 AND guild_id = $2
`

type GetUserLevelDataParams struct {
	ID      int64 `json:"id"`
	GuildID int64 `json:"guildId"`
}

type GetUserLevelDataRow struct {
	ID           int64            `json:"id"`
	MessagesSent int32            `json:"messagesSent"`
	TotalXp      int32            `json:"totalXp"`
	LastXpAdded  pgtype.Timestamp `json:"lastXpAdded"`
	StmpdCoins   int64            `json:"stmpdCoins"`
	InHand       int64            `json:"inHand"`
	GuildID      int64            `json:"guildId"`
	Rank         int64            `json:"rank"`
}

func (q *Queries) GetUserLevelData(ctx context.Context, arg GetUserLevelDataParams) (GetUserLevelDataRow, error) {
	row := q.db.QueryRow(ctx, getUserLevelData, arg.ID, arg.GuildID)
	var i GetUserLevelDataRow
	err := row.Scan(
		&i.ID,
		&i.MessagesSent,
		&i.TotalXp,
		&i.LastXpAdded,
		&i.StmpdCoins,
		&i.InHand,
		&i.GuildID,
		&i.Rank,
	)
	return i, err
}

const getUsersInGuild = `-- name: GetUsersInGuild :many
SELECT id, messages_sent, total_xp, last_xp_added, stmpd_coins, in_hand, guild_id FROM users WHERE guild_id = $1
`

// Every tracked member of one guild. Used by maintenance passes that need to
// diff the whole table before writing.
func (q *Queries) GetUsersInGuild(ctx context.Context, guildID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.MessagesSent,
			&i.TotalXp,
			&i.LastXpAdded,
			&i.StmpdCoins,
			&i.InHand,
			&i.GuildID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importUserStats = `-- name: ImportUserStats :exec
INSERT INTO users (id, guild_id, total_xp, messages_sent)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id, guild_id) DO UPDATE
SET total_xp      = EXCLUDED.total_xp,
    messages_sent = EXCLUDED.messages_sent
`

type ImportUserStatsParams struct {
	ID           int64 `json:"id"`
	GuildID      int64 `json:"guildId"`
	TotalXp      int32 `json:"totalXp"`
	MessagesSent int32 `json:"messagesSent"`
}

// Overwrites one member's XP and message count from an external source of
// truth, creating the row if this is somebody the bot has never seen.
//
// Called once per member rather than as one bulk statement, deliberately: each
// call is its own auto-committed transaction, so a row lock is held for barely a
// millisecond and the live bot's MessageSent never queues behind the import.
// Batching every row into one transaction is what made a first attempt block the
// bot for 21 seconds.
//
// Coins are deliberately absent. stmpd_coins and in_hand are this bot's own
// economy with no counterpart to import, so an import must not touch them.
func (q *Queries) ImportUserStats(ctx context.Context, arg ImportUserStatsParams) error {
	_, err := q.db.Exec(ctx, importUserStats,
		arg.ID,
		arg.GuildID,
		arg.TotalXp,
		arg.MessagesSent,
	)
	return err
}
