// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCoins = `-- name: AddCoins :exec

UPDATE users SET in_hand=in_hand + $2 WHERE id = $1
`

type AddCoinsParams struct {
	ID     int64       `json:"id"`
	InHand pgtype.Int8 `json:"inHand"`
}

// Either of them seems redundant
func (q *Queries) AddCoins(ctx context.Context, arg AddCoinsParams) error {
	_, err := q.db.Exec(ctx, addCoins, arg.ID, arg.InHand)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(id)
VALUES ($1)
RETURNING id, messages_sent, total_xp, last_xp_added, garrix_coins, in_hand
`

func (q *Queries) CreateUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, createUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MessagesSent,
		&i.TotalXp,
		&i.LastXpAdded,
		&i.GarrixCoins,
		&i.InHand,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, messages_sent, total_xp, last_xp_added, garrix_coins, in_hand FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MessagesSent,
		&i.TotalXp,
		&i.LastXpAdded,
		&i.GarrixCoins,
		&i.InHand,
	)
	return i, err
}

const updateCoins = `-- name: UpdateCoins :exec
UPDATE users SET in_hand=$2 WHERE id = $1
`

type UpdateCoinsParams struct {
	ID     int64       `json:"id"`
	InHand pgtype.Int8 `json:"inHand"`
}

func (q *Queries) UpdateCoins(ctx context.Context, arg UpdateCoinsParams) error {
	_, err := q.db.Exec(ctx, updateCoins, arg.ID, arg.InHand)
	return err
}
